---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: deploy/chart
      version: 0.0.19
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner-charts
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: rancher/local-path-provisioner
      tag: v0.0.19
    storageClass:
      create: true
      defaultClass: false
      name: local-path
      reclaimPolicy: Delete
