---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      image:
        repository: grafana/loki
        tag: 2.4.2
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 336h
        ruler:
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          ring:
            kvstore:
              store: inmemory
          enable_api: true
      persistence:
        enabled: true
        size: 5Gi
      serviceMonitor:
        enabled: true
      alerting_groups:
        #
        # Mailu Postfix
        #
        - name: mailu-postfix
          rules:
            - alert: MailuPostfixLookupFailure
              expr: |
                sum by (app) (count_over_time({app=~"mailu", component="postfix"} |~ "lookup failure"[2m])) > 0
              for: 0m
              labels:
                severity: critical
                category: logs
              annotations:
                summary: "Mailu Postfix reports temporary lookup failures"
            - alert: MailuPostfixStartupError
              expr: |
                sum by (app) (count_over_time({app=~"mailu", component="postfix"} |~ "FileExistsError"[2m])) > 0
              for: 0m
              labels:
                severity: critical
                category: logs
              annotations:
                summary: "Mailu Postfix startup failure"
        #
        # PostgreSQL
        #
        - name: postgresql
          rules:
            - alert: PostgreSQLReadOnlyFS
              expr: |
                sum by (app) (count_over_time({app_kubernetes_io_name="postgresql"} |~ "Read-only file system"[2m])) > 0
              for: 0m
              labels:
                severity: critical
                category: logs
              annotations:
                summary: "PostgreSQL has read-only file system"
    promtail:
      serviceMonitor:
        enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists