---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: 1.6.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb-charts
        namespace: flux-system
  values: {}