---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.authelia.com
      chart: authelia
      version: 0.6.3
      sourceRef:
        kind: HelmRepository
        name: authelia-charts
        namespace: flux-system
      interval: 5m
  values:
    domain: ${SECRET_DOMAIN}

    image:
      registry: ghcr.io
      repository: authelia/authelia
      tag: 4.32.1

    ingress:
      enabled: true
      subdomain: auth
      className: nginx
      tls:
        enabled: true

    pod:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
      extraVolumes:
      - name: users-volume
        secret:
          secretName: authelia-users
      extraVolumeMounts:
      - name: users-volume
        mountPath: /config/users_database.yml
        subPath: users_database.yml

    configMap:
      theme: dark
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users_database.yml
          password:
            algorithm: argon2id
            iterations: 1
            key_length: 32
            salt_length: 16
            memory: 1024
            parallelism: 8
      access_control:
        default_policy: deny
        networks:
        - name: private
          networks:
          - ${NETWORK_LOCAL_CIDR}
        rules:
        # Disable Authelia for local network
        - policy: bypass
          domain: "*.${SECRET_DOMAIN}"
          networks:
          - private
        # No public access
        - policy: deny
          domain: mail.${SECRET_DOMAIN}
          resources:
          - "^/admin.*$"
        # Applications with built-in auth
        - policy: one_factor
          domain:
          - mail.${SECRET_DOMAIN}
          - grafana.${SECRET_DOMAIN}
          # - rancher.${SECRET_DOMAIN}
          # - bw.${SECRET_DOMAIN}
          # - cloud.${SECRET_DOMAIN}
        # Applications without auth
        - policy: two_factor
          domain:
          - longhorn.${SECRET_DOMAIN}
          - homer-config.${SECRET_DOMAIN}
        # Applications without auth but low security requirements
        - policy: one_factor
          domain:
          - homer.${SECRET_DOMAIN}
          - prometheus.${SECRET_DOMAIN}
          - alert-manager.${SECRET_DOMAIN}

      session:
        name: authelia_session
        same_site: lax
        expiration: 1h
        inactivity: 5m
        remember_me_duration: 1M
        redis:
          enabled: false
      regulation:
        max_retries: 3
        find_time: 2m
        ban_time: 5m
      storage:
        local:
          enabled: true
          path: /config/db.sqlite3
        postgres:
          enabled: false
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
        smtp:
          enabled: false

    persistence:
      enabled: true
      accessModes:
      - ReadWriteOnce
      size: 100Mi
