---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.14.0-debian-10-r28
    auth:
      username: authelia
      password: "${SECRET_AUTHELIA_DB_PASSWORD}"
      database: authelia
    primary:
      persistence:
        enabled: true
        existingClaim: authelia-postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
