---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.14.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    postgresqlUsername: authelia
    postgresqlPassword: "${SECRET_AUTHELIA_DB_PASSWORD}"
    postgresqlDatabase: authelia
    persistence:
      enabled: true
      existingClaim: authelia-postgresql-data
