---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 15.7.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    master:
      persistence:
        enabled: true
        existingClaim: authelia-redis-data
    replica:
      replicaCount: 0
    metrics:
      enabled: true
    auth:
      existingSecret: authelia
      existingSecretPasswordKey: REDIS_PASSWORD
