---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: networking
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
