---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jd2
  namespace: vpn
spec:
  interval: 5m
  chart:
    spec:
      chart: jdownloader2
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:
      repository: jlesage/jdownloader-2
      tag: v1.7.1
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
        hosts:
          - host: jd2.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        size: 1Gi
        mountPath: "/config"
      output:
        enabled: true
        mountPath: "/output"
        existingClaim: jd2-output
