---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.09.2
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "homer.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "homer.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: homer-config
        mountPath: /www/assets
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.11.1
        workingDir: /www/assets
        args:
        - --user-data-dir
        - /www/assets/.vscode
        - --auth
        - none
        ingress:
          enabled: true
          hosts:
          - host: "homer-config.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "homer-config.${SECRET_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /www/assets
