---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
  namespace: default
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
