---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.6.7
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    replicas: 1
    hostname: rancher.${SECRET_DOMAIN}
    tls: external
    ingress:
      extraAnnotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
        external-dns/is-public: "true"
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"
  # https://github.com/rancher/rancher/pull/35698
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: rancher
            patch:
              - op: add
                path: /spec/ingressClassName
                value: nginx
