---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/latest
      chart: rancher
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  values:
    replicas: 1
    hostname: rancher.${SECRET_DOMAIN}
    tls: external
    ingress:
      extraAnnotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
        external-dns/is-public: "true"
    bootstrapPassword: "${SECRET_RANCHER_ADMIN_PASSWORD}"
