---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.17
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2
    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${LB_IP_BLOCKY_SVC}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${LB_IP_BLOCKY_SVC}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
    config: |
      upstream:
        default:
          - 1.1.1.1
          - 1.0.0.1
      customDNS:
        mapping:
          nuc8i5beh.${SECRET_DOMAIN}: 192.168.1.10
          nuc8i5bek.${SECRET_DOMAIN}: 192.168.1.11
          pikvm.${SECRET_DOMAIN}: 192.168.1.12
          proxmox-bs.${SECRET_DOMAIN}: 192.168.1.13
          nas.${SECRET_DOMAIN}: 192.168.1.15
          proxmox.${SECRET_DOMAIN}: 192.168.1.10
          mail.${SECRET_DOMAIN}: ${SECRET_VPN_GATEWAY_IP}
          ${SECRET_DOMAIN}: ${LB_IP_NGINX_INGRESS}
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
            - https://raw.githubusercontent.com/mmotti/pihole-regex/master/whitelist.list
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:192.168.1.1
      prometheus:
        enable: true
        path: /metrics
      bootstrapDns: tcp:1.1.1.1
      httpPort: 4000
      logFormat: json
      logLevel: info
