---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pod-gateway
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.3.1
    addons:
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210424
        env:
          TZ: "Etc/UTC"
          IPTABLES_BACKEND: legacy
          KILLSWITCH: "false"
        configFileSecret: pod-gateway-vpnconfig
        resources:
          requests:
            cpu: "0.001"
            memory: 128Mi
          limits:
            memory: 512Mi
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(curl -s https://ipinfo.io/ip) = '${SECRET_VPN_GATEWAY_IP}' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 1
        networkPolicy:
          enabled: false
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 8005
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: ${NETWORK_K8S_CLUSTER_CIDR}
            - to:
                - ipBlock:
                    cidr: ${NETWORK_K8S_SERVICE_CIDR}
    routed_namespaces: []
      #- mail
    settings:
      VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: false
      VPN_TRAFFIC_PORT: "8005"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR}"
      VPN_LOCAL_CIDRS: "172.16.0.0/24 ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${NETWORK_LOCAL_CIDR}"
    publicPorts:
      - hostname: mailu-front
        IP: 2
        ports:
          - type: tcp
            port: 25
          - type: tcp
            port: 465
          - type: tcp
            port: 587
          - type: tcp
            port: 143
          - type: tcp
            port: 993
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
