apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-secrets
    namespace: networking
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:cp2SRgVS4CaUqTZ6qRkmIsVv1wjIS3+nZ+hxGyUao+JoTM1Y6y4htfp5lPGhsCVSEp9O3laO/HK67uIhYYRf/LWy2MFn5gjt8+e5321vtVM1U0JGKYNMYROGBb3em9vqKQ1I3dyzq8kulwauDJ8tBbr0LgmxOoTI5hxAnJuEAtjpVkD7apDfFgAS73MA1nuY7dLFUSwVMXwey7HiHr1HFr07CvdLz7BCtqblX7zbHkl887MtaeSqftUFqL+Wk8qLA8aIn3Yex+qXX+6iZLKki+cOpIFUPGVSpuN+JfNDqfSspJcu1RmAat35aXr598MUeLU+wGN1VC1HqC3t,iv:Crl8/E9mAolWr31KmkVmEiJQB8AgvTteKg4pJ8Otldk=,tag:2RJzHx7mIAlRawcrSTHJPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-03T10:23:51Z"
    mac: ENC[AES256_GCM,data:9HjKtl3QVHNILQtH3H6TcjzFbrA3Qzx/RTze9EptpIbAbd9Rm/rIQClKzqGhk0IiN9dfHuzFAmdZ24ExDdoMGWvJT/t+vTGuaUw3tKUGUC4MvEKs81OnH8Mm49gra4oy5hNy6/E8i/4P6QUiKny+elDEuf66NFm1XJNDdHjjv7w=,iv:wjIKPrv19D5SMj0UcepRj9Oo8QVraGj8gBbDisDBBag=,tag:xxEFJ9XXLBHCk8VMlkSMPQ==,type:str]
    pgp:
        - created_at: "2021-08-13T11:00:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63ARAAsdxAT7FRIN8smznS7mE6jB/w5g8XEV/Fasm6+itWBcKO
            I7HKEI6tBI6gRVE6txCZd7Kz/xViYAC8BSNur8NzTL49ORYiISsWCOED9QOE1VJs
            0w2itFrlC0CrgU8jnIbcTPLMUkSNeT1H8lCc4JgXEbK4k8RB4YWIW04SuT0k2mD4
            slrcHaGchsoks0iVxSaGndSjSU1vlQG9joYAfaf0CIpmA6fpPRCs4MrjhCpC+Tj5
            XqpoNlly2ktydFIYlkQECGLp9Fh2UNVwCEItaPcYqWW9NZZTyElWwESmxnyum5CO
            jj2rFB9EIon+XTij7Otk7qR6h1mBpQFAsp0H+55EQthg3Iy8gBAUSJ8zRM5tAoch
            0wznAHQLrHPyEmMs4/PNFIjgA16cC6K5zm4Q9KlLQyHl5Vl7+UwRW4lB2mky5ivi
            XUACrRhuTKrrHnCc+Gdu769T1WrIxFF8geLcNIRRkDc8Wihzw9b6OZwSy4O4zTZW
            WeoYVznWjH9kC50ATbxlZx9iZeAu3CvjAvaRaatXafeoYTfbbrnXAMM3Z1rOka+6
            RLcRnbWbeQuDk8bC+mymGW4JosM81yMVqdZArdkB17BeN+VVOpZuvcfnmG/8xhMH
            I0eEWdlAFojOetWwRgGSM9ZnnWHy5WrQHwGswkD20fS2aBVpEEQuuoILuyN5MZ3S
            XgHCUe3HIEmWF9fIbXVGO0NQeEnmDKlZHUKF2WZ1edS3nE3KAEleb5OUgg2zT0rd
            88CI6evgZdcKDcEFh+WimMmBeXlCxeR491i7JDDZwuJVnGumJ17a12LePUEcxhc=
            =HpG6
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2021-08-13T11:00:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA64B9baa/LIjAQ/9HJaajuLlklIBIE5+Vg8JJ4Ps3MMsya89IJnK6LS13XPr
            YzrzbgEnFfZ5ofvTmRMqG6kQHsXfpFPmS1gpIhqA47JCQj5mjwu604Gm9pGBRkB7
            xabVNJ+RPi1fK3ATduYsIdLfGeNBRAhVxO3v2NJpQs0B4rudvCg3O+1ANsKxW92m
            hxXzGpxj25/iePyS1XDScB9av6Kb3qA3bn3/AvdcbqfUOb6H4HEa57FMkUL1EZsr
            FzBtjLUgGSn4/iC3OiCpZBMa8VWAdVDRas0NOLPdd0eX0zIGBhoTjGXuItXMXng2
            Dur3aUCc0tpNZkKu1B0BhoBWMd3XzQXpD63SLxpSIlt5XykunriFVj1IZVXPGEh8
            GApidF4lLiWLkmd3jTZ7lunZmDa55VbJnlSFlDdBirtjodCda0ByhzKsJORqSC53
            9zG9pmtav5xN8OHK9YV9ViQnrggcwhQAMdM1msv53joQ0xkJp5grpgt7QMLrKD0o
            sACx+dtrz6Y7nrOr7JALKsBZ4oStiSNJlRJP2ODP/8Tzo/pR5ju/gQnnrMpA0pKv
            wDk9oCcxjuDk998QgTKhNwEZwkiXmpBZIF4iQPM/Cd5lizDxeUZKkjluq7ObTKYn
            PsGxzqyOzeKmk7Xh3MbFVekCXCJrLatzxsl8Ydw0zcHo2crJ4LfZwSfE9kalNvnS
            XgHtMiV4kjaI4+mUj5+CNXslETLqesX66EckhT7k5+6oSgZhGTg4bMn3IjbKgu7K
            7j6TzidMblPeAkftTlQIpn9UAMcMi62hDipO6r30iNW8WSKhRovgqygPGsIQR0I=
            =MBR3
            -----END PGP MESSAGE-----
          fp: EE1FCDA1BD7E34481E71FCBFC72AB78A7F05099D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
