---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-paypal-importer
  namespace: selfhosted
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: firefly-iii-paypal-importer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firefly-iii-paypal-importer
    spec:
      containers:
      - image: ghcr.io/pumba98/firefly-iii-paypal-importer:0.3.1
        imagePullPolicy: IfNotPresent
        name: firefly-iii-paypal-importer
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: APP_TIMEZONE
            value: Europe/Berlin
          - name: FIREFLY_PAYPAL_ACCOUNT_ID
            value: "1"
          - name: FIREFLY_URI
            value: firefly-iii:8080
          - name: FIREFLY_TOKEN
            valueFrom:
              secretKeyRef:
                name: firefly-iii-secrets
                key: privateAccessKey
          - name: PAYPAL_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: firefly-iii-secrets
                key: paypalClientId
          - name: PAYPAL_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: firefly-iii-secrets
                key: paypalClientSecret
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-paypal-importer
  namespace: selfhosted
spec:
  selector:
    app.kubernetes.io/name: firefly-iii-paypal-importer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: firefly-iii-paypal-importer-cronjob
  namespace: selfhosted
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
              - /usr/bin/curl
            args:
              - --silent
              - --show-error
              - --fail
              - http://firefly-iii-paypal-importer:8080/sync/1
          restartPolicy: Never
      backoffLimit: 1
