apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secrets
    namespace: selfhosted
stringData:
    appKey: ENC[AES256_GCM,data:C7HxLBsjmGrAZX+p+rmlNduRm2tw/bllM6Sz4kC3wG8=,iv:m0ifoSzKtTj2vc+3V4aQcicDUQjZ7z77nPDYimPgyR0=,tag:Quwz2nPF9643aCbktPHdVA==,type:str]
    staticCronToken: ENC[AES256_GCM,data:pwQpXiQj3y1xpNhkdi31iFIGaPUj9HAYT5aQGYx0nEk=,iv:sC5+QVkIsjoyjg2yosNXoOJkmVBpDHvJNK4BtYRj6aE=,tag:imHFRUp1YrtNI6xQKaEX3w==,type:str]
    privateAccessKey: ENC[AES256_GCM,data:RhVq49l6ExMiL97lAI0fi9ANd84LiTEC8Rty3wDo2w08TyOYBjm6YK6ieDo761rdaW+tqVPJEcXNjf+zFn6D3jKdnbXMnQyWDj5FHqFlwfVOJMeEcdfpzXJHd0rg9K45+/kbk1DDWCk0WB/iI/L8FMAC+Vm5fZimF4N7PJv7z6QqeiQvRkrZ7GDy/ZCt0Q3bLP6TxICGxwC3LjLEyvfGDH25gC7gML19UTlxTUHtP+rzMCicmY1Oi3mybLfsfHxtorxT4AEpKaQqgO2JZlIQbUkClpU027YYjXubwWGA1Bfwz8USdUh75AzOfKQSVHDx7q93CaiMsiKbJRMK1wZWm5Rk+nEVZAwYhgIdv9cFeVFVZ2meiJmGrvJ/rErRhn9c1asdaAAPhoHybdvtss6+IzYyHmcPX5KlijjbM5oFkSrbybEKYYBbkcLh24GBSX/7YW2U/Is6iNzXMSVsc0KPybivqT48JIVlvqdUGVt8N74yfpPKPaA+USQwiWxP8HkCojUJMJVvBwSjUkRaO7jlad9Dig9yCuC2WOnB4t+ZsWYB6IcWsCMbdghTg20zWkSGn+h42JrYjO1yCDQIPJU5ZEKKwmoQU6k67D1s70icqeb6WtqMKu0DbpuRdSQExXKxwE1qRiqkPnpdh15Nhmx4GZPlsipBZMm3Lgm89svhGUYPGIbc1onS7WAIPfLu2dA1aHZPrseyrA5/KDiQVs+smYhFgR7iSVqvXDcpmn5MjMbHYSHfRy8U6cNqdHu7v96sokhcALJBYvqoI3WPPZZUCQr61D/OsBlAcqNEITGe/vJLc4pzbcK6H2FtNO/Vd6tTxwS1De0r5/rQn5g2Q38zfUj0CbIRaHpGa3yoiIanyVsUrjUhyRq2MLDKPD4lca6xQyOPtrrF8elU7+3mTrNQCx/ffnsDrSO2FOexc6S8nrfe8jkwu1ktvdDlCBUfBLaVVX4LiCMiwMdy7zipoSJCgFkUCbc1Yu0cmSmXbnv0/N10WnRxRaI+4/KN6/c8JzSa80jGnKWjNKw+gw4zoYQcYfNrYYZahErLn79M3p2QkbPQFnxo+kIsdHkSI5N78N0SnYTQBav6qihCYgZ/D/tF6WcIHG72J6YFnW/mE/CxQ8S/t+YHQuOlJFbLlD5Qs6tx+xGr2HfVQCRV/l4izCs8FdYG0hERflaCS7u2ScRg1YME55C2TVAdDnPecc1mjWWbtU0PyaxSU1Mo/xVw35n6hgcFm7LaMU8ADjf/I/t+zIhx6CkFDc+T/goQwaZUhdBrZyL9Z0RTwEBgJmUApG0P2j7s+i8=,iv:kzGnn/Il3hSP5MkJ6HOZqGErJaKXwxUDceMgEdD38Lk=,tag:FLYH3mAfLO4JVIOQqIIukw==,type:str]
    fintsConfig: ENC[AES256_GCM,data:o1F3S9MMxA/gCZhyf+zb49rR7tg0P8XZgnFrOEhc0f5Ip5ODylfWnCrdxZoNy8wk968l60a1h91INlZjnO2M9TMNg4vAlJOzTV17LNaT+uOhf+0cldEXiaw9J4/pwGJFDsfYb2myo1RBvBZJCMIQ3E3F++JfxUWnirz3uGWNXmKKFqRprylsgBHPl7NuWNMt+vpfLFYR6ieXbDK2yZl+7hOR2ioKmNPr38uNbH4ozvQ1lEbiRICXIxHSq25SBsI25yzTL3u21nEPNeGTIiq32MEDdT5ckzcHpLbwPGKaP/+nngVRZpHICXDulyIZ67eazIxV6p0bQ0TXPDDrrT2MUb7D4jMIQRHZjVKV1AwpyJ7z+a/reLhlyMndEDcFw0o2Hpa3oLlSlm0kOqs+Xc8ztva1XM+mXxCMfKjk054NhDiTAcHG8tBQi9H5Skz0TmoY51txqjIVv5ztsBDnwVcovpsfYc00MMUeA7SHMP6CIEXXHiFjOXlbSvllkdGBrIotvJvMXsijU/pf85iAFeGa02/zOnHlSgSXKnmeLK/gna4HMSKVxZDEdtlfcJ5nV+xU/nfy5Yf1LqLycH9E+IUJA/KBht+URd/wBX6pJ4TNherAre2WKgrfdMwfoUBkuO8n6beIzpEiT82Vz8Mu0wVOvu0q+6rkbreq9ajUMzAiEf51B1QMhrUwJRdLS16VsPfKwPyjwJXVIfGvoAQPBUKL2KUq1UtTI/VZv2HNjL6sULleS2EHaaRcq7m5XAZIPJcAUXBVlyr0Or02k3PfSg//OUHTlUnzO7R0qe3fphxEsCZZiPHKtV6qnE1DLJH3bAtNCqE0BAWqajUMc9YtLJCs31WSb/DMnAxpWCqBfTGBwWExxMi49c9q8GyeSSRD3PPYNWJxQoWIZFoq83Ut5vfJ2bc/W/wsIzzoDz6NP6r3/7QTIXUBQsoyTeaoHYzghlJRAR1dR8eoTZSgP68r7462irSCuhlivBTNnhOz6U4i6CbtxuQcqWWXKqqiEwEfBB3UL21Gx2ZaHOXbDhnD+/ltmr4FjumNF8C3aBFEazoL55a14zk7D7cJ/zvdC1mpkiXPRYlYRAwT6tl/kOuwvLoN9OBVwjFzDZ96+DQYWER+950B26pXj/BBrOLI7u40Sz15QwT7H4BKmb2UIyq6CFYCk76HlZRde/iHckcNxpaaFqLbOlzHRTczfgwCBJyzv7s2+GLhSANIEt/yOgh3JAHOWQsa7DztsxzFtHPescw7f40/84ERe5LBr8r01xH4ruSlXWuhwfo4n8E991ZxXJ8dT/X9j9vWn42lbQjA2dIHJ7qi1pjjzLu7x+f4yMQIycLesYsaQo3w0V659Ea18sAiPI9a/0aA6Uyt3ECBvSA854b0VSq9SxJGWGydEVa4mA/RwoM3DbC16VzrJAKjBwROE/sP8XSZJmTdNOWz01F+DVrTO/v6bKgr8sL1+x6fvE9MlOYRuv5eJq3B3GYj2bA34Yg5WagVFNxDSQNuedFHrL909w2DljIawfcHK7os8EB053ouWT3M1tQnqBWIXC7XIJtVMV44NSdvCT+OkIes5Se7wWqZh68Xz5B/JYmJqrDbw+tYgb6bES0dIPAT9oS05yqpar4NOqIJsrKlPHIvoOWQPNYDHX1HMHYgIn9ntCR8SqqruZ7TKc4+HvQeMwYP5FTEEgUwJAYkEFGxbonSywCp1ILHz28rtUqpzGL6cP4BYmV2T2il4JmfiVHB1WTutWp0/O+5A2FzONNyXfI3XkqT+KHiLTuN7rHPYJKPv6AVby8o7qX3NwDtPZzBMlhz450OvqSAbDWuQbuuECgS1MUNR3vFLCXl0g61UXgek5Rn01dnQKK9z2391EJY9c1Efiyq+RjlE51fjUYlPzHZfyXCxyOcwAIpddxlv0TlPlG8nuwqsoBPP/FJxHrMi97bJcMeR2QD0KQFGNx5rtJzJPkbS69X/Dir8+o+/caNkyL3QrfVqFX/8XNNite4IJEv1/vVX/m4i/JNWeQMJJUyM4WYCkrzjtRMJOwp7rvBTXw3vPyPCltp2nbombA4JOZv1t4XhAl1srXP4GBESdlKVXmh5BBr3TSQSN7KQTmq19Mq5p9onX17VQ==,iv:WsjcFQfB0uC2ZdLrTt12sOm2qGZjg2yKvp5cgcCAWo0=,tag:AlKfM/AKvcEkIHUU8s/+vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-07T13:43:35Z"
    mac: ENC[AES256_GCM,data:ZiqbNJNOI9KBEgky2aRiG0Vpy0XarkvUUh9gXIgKcOVmCQ2iM69TIsk4KD0M8Ud7l47Tjfc0z8xQpmwUzhXxRrhKPaZaQwuOkCw1+kVc6gdkgT8lPOj4ZgAKC/NWOxP9usAb2/M/7Fmd01PXgTSjv7AX3fofCePesqhjG/ul7c4=,iv:OjmAIaMyqHyZN/PSSNlKwb1Oo3S5aGM9URiPGXOqV9Y=,tag:DVuC5BKfLZoLDHDtPb1KFQ==,type:str]
    pgp:
        - created_at: "2022-07-07T12:20:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ/9ELoLNDXtK5ddJo0U/e+kAClGp3Wu9WQ/8Ff5inzpIR1j
            QRn6uvFkESU3StM79xb3Gmw1kP1wrUaoqKeqD2XIJtd1AtYkxfEyvh+ni1yZXZL+
            9seTnmcRUCIp6MDtUKsuWyp1w/AbNtDCO1QKa0I/0zAbN/nVQK7eDzKR/ghc36dB
            1Ws8UriKqticFZRQy8ABk/RHR0tu27NGkl8F6fA2iqyuhF37vsJTpvRUwvufUcSh
            TaTlJ3dajOGML1/BgBhdN8sU43QEpfJ3l0x7Ir9uUJLPVp/WmPgIyqmW+Kr6W20Q
            gh/HCVFbpIeCH3n0b8ZvB6mQGIeSsGzMlSnzQpHyTqxbgY7+UjxN5AEeNtgdBjpa
            vtRHkGuAWZ1O+Iz/hD3RkHajNT2bUjxotky2SI54RFx5/2999pn3K24M/uyjG7pJ
            H8TTH76YahShaBOGRLycYF3njby7ACL8zfRhmDrR4Yhf0tKxCNJmZlUhKQB/hWNH
            7e2BN9XhrO5cbQRFThcFSRGqcrKXBH9fMvu8Xz7AfFixzDhEtT817+bfEENyVh7o
            zkURy7nqFURb2zpWI9pwi/mWYORmPpuSa92kCY0rljOASgKZVsPDIY0/a8GsOUhG
            hD3jlZSx0lh8aQzDrnEIqoe/geGRl3oXhmrd3cFz5rHBaSO6ACcL+5vdOmOiK7bS
            XgHxcKcriYEj2HeKP8xWGclGrrdairRlkuI+pZ/kYSIW3waYpf+D3N08aUJExa8V
            vkYKdCY9lzvpmcaTPlzsE6EEhNHJZVJ80qlscF7zE4Fh3zY7rV2+6UuUd2DsBJI=
            =jmgu
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2022-07-07T12:20:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3cpxTiGWvJJARAAl+LKKC0CZrfjsumiO0VVuEfioa/eSKS+1XpgsEjzIgYR
            WPOC6n5XPuv7P64ssThZPOGRt1GZxJtQcSZmcaT3/g0GHbof1FXLfwRU7DQ+BMI6
            C1nB73ORZkLIEDh5IbZ4oreiAcCZ9IgAcuAuDRCA8dWaJIqMGJUIR8NHKhAnDZlJ
            ClDfhHOe2hBEpZXdNS5WLPkvSH27ehhA2lB1ouWdDehwiEMgg4iaQcstaCfOiOto
            rW2jQ8gukWXn/LkUfyDgYfFn2ZuST8SG7CsfS8UIVpykVZKvIhCrxS6hzAk2czQe
            9STDooPjgJtAvDrwDtBp5MuRSAFODfVA4f8PMDNT1cJqEBFI8+X9ccR1tdvg0QqO
            0NyQNIiFPrgpKCWELhdSKBMgtkGOuZA1J5spZkw2KXw3A6fL1y0RTi71WDmrOydw
            8gAf9Vs3z1rV/E8Yr5pP7Ih+OOG6Z2kFZ4xCbQ8ZCrGutpyz9896CVDHhyfw0akS
            Y9AfmTjouud94ClnR/TsnCTXHsuxF8EEXsOTUMgSxXj5d+K1wvNmofndCSoUMKCm
            kZLNLJVXO/1j4d+tyP3VjMt0QF9jGl5OYlw0I+KAl4RhaOgJtMcOr2xS4ht7Eotv
            AHYVD2lZMfzRvUgnG9umfDWSJc0khl2F/GpirhF/eN0w0NsgqEuVRmDvc7Y0pjzS
            XgHyym2Ie20Ah7j/TFIMzITyk8Chzdus4uWLoQvt5gW9hb9dtZp2aIY9E5/C59sW
            i6nN0rIcaFTbFE77VtINe8alVlfQuytodaOKv9/Qr1uU8ZgUtYC7vWJmMvD+03E=
            =0NTH
            -----END PGP MESSAGE-----
          fp: 8D200BE9B98597BE5D53AC63586602C2843240C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
