---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-postgresql
  namespace: selfhosted
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
