---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-fints-importer
  namespace: selfhosted
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: firefly-iii-fints-importer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firefly-iii-fints-importer
    spec:
      containers:
      - image: bur0k/firefly-iii-fints-importer@sha256:f1b49a14bf982c1ab1dbde8743514e9afa5bd72e69828129a4dac6e65c7f3352
        imagePullPolicy: IfNotPresent
        name: firefly-iii-fints-importer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data/configurations
          name: fints-config
      volumes:
      - name: fints-config
        secret:
          secretName: firefly-iii-secrets
          items:
          - key: fintsConfig
            path: config.json
          - key: fints2Config
            path: config2.json
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-fints-importer
  namespace: selfhosted
spec:
  selector:
    app.kubernetes.io/name: firefly-iii-fints-importer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: firefly-iii-fints-importer-cronjob
  namespace: selfhosted
spec:
  concurrencyPolicy: Forbid
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command:
              - /usr/bin/curl
            args:
              - --silent
              - --show-error
              - --fail
              - http://firefly-iii-fints-importer:8080?config=config.json&automate=true
          restartPolicy: Never
      backoffLimit: 1
