apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: selfhosted
spec:
  releaseName: firefly-iii
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: fireflyiii/core
      tag: version-5.7.9
    service:
      main:
        ports:
          http:
            port: 8080
    env:
      LOG_CHANNEL: stdout
      SITE_OWNER: mail@${SECRET_DOMAIN}
      APP_KEY:
        valueFrom:
          secretKeyRef:
            name: firefly-iii-secrets
            key: appKey
      TRUSTED_PROXIES: "${NETWORK_K8S_CLUSTER_CIDR}"
      STATIC_CRON_TOKEN: ${SECRET_FIREFLYIII_CRON_TOKEN}
      DB_CONNECTION: pgsql
      DB_HOST: firefly-iii-postgresql	
      DB_PORT: 5432
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: ${SECRET_FIREFLYIII_DB_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST: mailu-front.mail.svc.cluster.local
      MAIL_PORT: 25
      MAIL_FROM: firefly-iii@${SECRET_DOMAIN}
      MAIL_ENCRYPTION: "null"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
          external-dns/is-public: "true"
          nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/verify
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
        hosts:
          - host: firefly-iii.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 8080
        tls:
          - hosts:
              - firefly-iii.${SECRET_DOMAIN}
