apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: selfhosted
spec:
  releaseName: nextcloud
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm
      chart: nextcloud
      version: 2.8.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: 22.2.0-apache
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      tls:
      - hosts:
        - cloud.${SECRET_DOMAIN}
    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: username
        passwordKey: password
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array('${NETWORK_K8S_CIDR}'),
            'overwriteprotocol' => 'https'
          );
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_DB_PASSWORD}
      database: nextcloud

    cronjob:
      enabled: true
      image:
        repository: curlimages/curl
        tag: latest

    redis:
      enabled: true
      cluster:
        enabled: false
      master:
        persistence:
          enabled: false

    internalDatabase:
      enabled: false

    postgresql:
      enabled: true
      postgresqlUsername: nextcloud
      postgresqlPassword: ${SECRET_NEXTCLOUD_DB_PASSWORD}
      postgresqlDatabase: nextcloud
      persistence:
        enabled: true
        existingClaim: nextcloud-postgresql
