apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: selfhosted
spec:
  releaseName: nextcloud
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: 25.0.1-apache
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        external-dns.alpha.kubernetes.io/target: "${SECRET_GATEWAY}"
        external-dns/is-public: "true"
        nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/verify
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
      tls:
      - hosts:
        - cloud.${SECRET_DOMAIN}
    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: username
        passwordKey: password
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: "${SECRET_DOMAIN}"
        smtp:
          host: mailu-front.mail.svc.cluster.local
          secure: ''
          port: 25
          authtype: PLAIN
      extraVolumes:
      - name: paperless-ngx-data
        persistentVolumeClaim:
          claimName: paperless-ngx-data
      extraVolumeMounts:
      - name: paperless-ngx-data
        mountPath: /paperless-ngx-data
      extraEnv:
      - name: TRUSTED_PROXIES
        value: "${NETWORK_K8S_CLUSTER_CIDR}"
      - name: OVERWRITEPROTOCOL
        value: https

    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data

    startupProbe:
      enabled: true

    cronjob:
      enabled: true
      image:
        repository: curlimages/curl
        tag: latest

    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    internalDatabase:
      enabled: false

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: nextcloud
            password: ${SECRET_NEXTCLOUD_DB_PASSWORD}
            database: nextcloud
      primary:
        persistence:
          enabled: true
          existingClaim: nextcloud-postgresql
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
