apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: selfhosted
spec:
  releaseName: nextcloud
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm
      chart: nextcloud
      version: 2.11.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: 23.0.0-apache
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
        external-dns/is-public: "true"
      tls:
      - hosts:
        - cloud.${SECRET_DOMAIN}
    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: username
        passwordKey: password
      mail:
        enabled: true
        fromAddress: nextcloud
        domain: "${SECRET_DOMAIN}"
        smtp:
          host: mailu-front.mail.svc.cluster.local
          secure: ''
          port: 25
          authtype: PLAIN
      extraEnv:
      - name: TRUSTED_PROXIES
        value: "${NETWORK_K8S_CLUSTER_CIDR}"
      - name: OVERWRITEPROTOCOL
        value: https
    persistence:
      enabled: true
      existingClaim: nextcloud-data
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_DB_PASSWORD}
      database: nextcloud

    cronjob:
      enabled: true
      image:
        repository: curlimages/curl
        tag: latest

    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false

    internalDatabase:
      enabled: false

    postgresql:
      enabled: true
      postgresqlUsername: nextcloud
      postgresqlPassword: ${SECRET_NEXTCLOUD_DB_PASSWORD}
      postgresqlDatabase: nextcloud
      persistence:
        enabled: true
        existingClaim: nextcloud-postgresql
