---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yaml
- nextcloud-config-pvc.yaml
- nextcloud-data-pvc.yaml
- nextcloud-postgresql-pvc.yaml
- nextcloud-secrets.sops.yaml
