---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-static-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0770
    - file_mode=0660
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: nextcloud-smb-volume
    volumeAttributes:
      source: "${SECRET_CIFS_SHARE}/nextcloud"
    nodeStageSecretRef:
      name: smb-secrets
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: selfhosted
spec:
  volumeName: nextcloud-static-pv
  storageClassName: smb
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
