apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: selfhosted
stringData:
    username: ENC[AES256_GCM,data:R/mObUEmdQ==,iv:d/8vArz4dWZjd5YDfWDxuvi805sXv1vFCQexTQm2Jgo=,tag:0+eaRcxDlQBk5d4ZY9CxJA==,type:str]
    password: ENC[AES256_GCM,data:C1jzA9pcUcZKBFunf5tsxQ==,iv:CJQUpNygecg2E2UEaX3V5MiPpuDwxvRs631LrygBDKo=,tag:zKuokfR52oVixL28Lwtnmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-20T18:06:41Z"
    mac: ENC[AES256_GCM,data:+tvrNM2e9W6oxE4kvWU1Y4BChu0mD8MzIqCAe5iI3SrnW+DucBSjNuMArILkAysm+1LVuwJ/fklaixMAaMyklYk78i/kJi9kU4scJ3/23xRz+dIcNxPl/LBvmBaa0k4+9vT09VhYr3NkTn8nlDRtJGbrt+SD3H9frkOYHS+jm40=,iv:JLP60M0lo+5sfsJw53tl/ul8bzMgATkfhIzBOTPm+0o=,tag:MUIUu0HlJpM94BDfISxKiQ==,type:str]
    pgp:
        - created_at: "2021-07-04T18:18:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ/+IUGDdVt+Urcof5PZXmpFLKXzhbhdg6bnz41n24eMjFr2
            36UowOPHC48w5CmBCq/Z/kIpjElAKunwrBkTznmN6rhTAB0N5Lm/dKTF1qYddQyw
            vp+TdwqY0FRt1ehG+JVzCRDnKzOjX7p9IqTmwztuEArIw1nPUXjg8gjekTwO1p7o
            mhOXUYdpdmRoH/0mWKeQrPYcQDzGVWadywV2rPuRc2EUFop+NFi+Ihw1JZFkncto
            OGB7vtKKJ1m6nCwLWbLQ38ISGESbrvW2osSTz2Jl2Bo/SA0PhDa83xbloowRfHCG
            HQPx5Kxf4yuemVAW82lzvkoVOBxwRQjqI+F+UM7qjrrmoFrxQGg6GjiGJCkJX3/x
            6cVw+MP0c6a8804PzWGIx8GeklULePrOYxl8DPa+/puHAbkfwv9TSKcEnT3Yh+qY
            ITuRSqqdiS2PW70+mDCVfDMtvx7lo6pKIY4mZnm8eyAQzMQzKMwrCACuxbyuR3oG
            UDz+z2bwM6raRegbh8Q7EP1eOdIBtH1JrOnp9oaP4FpXVdeuCxCA5CoZsNRRBzpi
            Evr/PCxL7AipZDi8BbdVCcRJvPH6XZ26hBqNabRs0+ZyE/cgvWYjFg85juyBdhIf
            afeJiX5NqM6NhqXjoM8tMdevqX4Efg+Gy+zgupUG54v8EaxkJ5fkPSSntm5DCt3S
            XgE/z+ThY/Y1qkU5EDrEp1opSFXctX2A6HSqO8mjmRvkx53xHJj2FfvVPAmbbNPM
            dDnv5jyLKWEMHXwSX3LuRfGek7zfml1sjHrnpYHFgGS9TJpjjBDORav07TcdgwY=
            =ZVuB
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2021-07-04T18:18:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA64B9baa/LIjARAAnS7exCSQINMHRDtmfHGF5s8qvnDpAMrt/EqCBoPgYiPw
            8Bah2EsTUePBNQlNYHMqgEI2yJYNdkjWm2npTRq4AgVuuL7x2X5oWThnI71s4r8o
            KlQ6IMtZC8XyagEHe/k96MKRkNDYctu09H9opZ1t+tVNaDRof+dRu9rcI9DGHpVc
            WIWw1jckhiIiip1J0wpy3UPQ6+tQRy4sQ10VK8flW0r16gg8u811yYlao+6mMr6Y
            Qt3aVkkzUGG/cn855Iu9GWITb4rYhaplpXTP6zBbP2izOhzw/FspwF9dyJZl2CX+
            yh1JVIxB1FkZOBJhfJGA9APrI3oBZggRl3LW4ZIjWL/9XxIKwJPRWjOfL4ESVDat
            KanX85OUMdZfiRd3COrrI/gCvD4PyIrNWOVMwslrw2ijDF/s/JXJDH4L6w2+qApg
            2Ehh3gDWHz84oyRONaGT9KRlYYWHzUY6H1rugFS+5IL0zbQLR/4AiLDFPWWvzSbD
            e0kIJYm9v6nAXLmhya4mNzH6Ukd3AMGgAunYtCdKoB7HJMWa2A1MhuutuRUii/EW
            HNyAqk+u+bAO4rDYuflS9jGzMkOUSc3UYPV2QcGLS2nyFP80qjbq9IlLSZ0FWpCo
            //339BAFAEzTn/khB5bpn3ypSh3/9KkcviHHxbVqUm0lpJjYGgpeq+nzT4wTcZvS
            XgH7pgR1bTOinrHR/HkVtIebJSolER0vSrMtsP/uKW1li+zRon4pJIvgOIv9g5ak
            pRl4pNewLPNBwOFpb7q7QF0pFzi8I8B8vQ5l7bK2unv/Rx7kA17+0zLqoMDbJME=
            =NPU6
            -----END PGP MESSAGE-----
          fp: EE1FCDA1BD7E34481E71FCBFC72AB78A7F05099D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
