---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NETWORK_K8S_CLUSTER_CIDR: 10.42.0.0/16
  NETWORK_K8S_SERVICE_CIDR: 10.43.0.0/16
  POD_GATEWAY_MAIL_VXLAN: 10.44.0
  POD_GATEWAY_VPN_VXLAN: 10.45.0
  PRIVATE_NETWORK: 192.168.0.0/16
  LB_IP_NGINX_INGRESS: 192.168.100.210
