---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NETWORK_LOCAL_CIDR: 192.168.1.0/24
  NETWORK_K8S_CIDR: 10.42.0.0/16
  METALLB_LB_RANGE: 192.168.1.210-192.168.1.211
  INGRESS_NGINX_LB: 192.168.1.210
  WIREGUARD_VPN_NETWORK: 172.16.0.0/12
