apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ReFgxsHYZMO0qmTv,iv:veuSRBMIxU3MwLt1uANzIPw1SU45k7LnbAgzcjkycSM=,tag:Y/qCj9g3lZpTWYllqK4uzQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Wn8I/SymciKXmnPlCfd9yuYqK2YDFw==,iv:DR39HhVD+UE1FtBDdRfTtMd7gSXJW9QmLzk20+pP4yQ=,tag:xKMqsUZctSF/VoEAUNdF/A==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:Dok9Pw6nbyXEu7cs4bcxJ8XKy+kApS4VH2MieXdFAqdGKYu1R9M4cFCpYHCsKJEyQXXMjpc6rqUAfgO5D1xCLeqD2emh87zgtaKOerzUL49HizNL8Adh5GCS5LViuwogDCtucBPIwcuQbjCk34GAKfdG+KgkBLs0WhtU2+/c,iv:ukXXriM11STTrbWsfKKtdGXRlGCDo39CyM2jrP9DGdQ=,tag:uRmCKSV8WdqaRUPdkXxW7w==,type:str]
    SECRET_GATEWAY: ENC[AES256_GCM,data:N2/eBQRVnRRcc33xXDAt07uHxHg=,iv:GOO/5xiUJJjosyX+1ZOmhl32dLf8O/By8KJ2SNUyZes=,tag:MTdO2QpeuBHeQNuPRYh1Rw==,type:str]
    SECRET_NEXTCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:zf8OCnXN8anSax0uIAYL5Thz94b6,iv:qfQLSFIhG0mv7mWcQQDdbInNMoixsZ/caMOK9eshRK4=,tag:mA0my2uAIMUYEK8tZtlghA==,type:str]
    SECRET_VAULTWARDEN_DB_PASSWORD: ENC[AES256_GCM,data:paFU4qwCdnh2w4o+KHC2yqI1viT8,iv:YqLRt5gxKZM0yKVk9BWJapSL2jJxXTqS4fhpwDcWVrE=,tag:XpvedUwpQM48m6wMHy6bxg==,type:str]
    SECRET_MINIO_ACCESSKEY: ENC[AES256_GCM,data:cFEIm7Mzb765t9aYRUfxqRrcDOY=,iv:vH2l32o4f8WHFgerj6BPEvKlgxG9skCtp0bKOmQNMcQ=,tag:MEq6Px8heMq7xGLqrOUgnQ==,type:str]
    SECRET_MINIO_SECRETKEY: ENC[AES256_GCM,data:qOK+HJtSEVEYKIHDr26NKk3LvkdNmuIeD1Bv9FPQrSQHgu2fI6kESQ==,iv:B2vlqstVU3pBtoitE8awQon9QZX1ba34zTEu3RNcArQ=,tag:2/8pVLkg+Ns2R6ajX6+nSA==,type:str]
    SECRET_MAILU_ADMIN_USER: ENC[AES256_GCM,data:mlXjTg==,iv:HA27I8Yi38/EFWpxSQCxnwWiwF8qhxmCscSpX+P/QAk=,tag:SUmH9wT/MwqZ2zPYIxA9VA==,type:str]
    SECRET_MAILU_ADMIN_PASSWORD: ENC[AES256_GCM,data:LE3lHSyC35kbjZxs2LpSwBcZlM7d,iv:rtNuggW21o5F/GyiOhcx5Ol+jflZAUA/CGyajC7bSZs=,tag:TuexbaTXygsQ6wTxNBbQNg==,type:str]
    SECRET_MAILU_SECRET_KEY: ENC[AES256_GCM,data:uVcBiAUG6wFFkABPdO0rV6tD8UOBFPEeXBh38g==,iv:3wiq5Z8N6x/LNoIPl4BJDhUX+sYZKcKXyEDQuFFI6Mk=,tag:uDlmJN3+jjElp+QiqfwvBQ==,type:str]
    SECRET_MAILU_DB_PASSWORD: ENC[AES256_GCM,data:706l15MX7ZKEv7UyoAjQu9etNV1PdIL3,iv:zVeGttXZRMcsBbDHY4+KmTrXFM3b9HILfWsRPcJQIu4=,tag:T1pYtmiGQA08eiVybkvHDA==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:n4+tTIZFQHW9H4CCLCk6Y12DZJSf,iv:GXERPGIJlEKejetouE4s/vLMmFGxMZheYNS9EQsmM4U=,tag:bicCTvz/FE55WeSzokqR7Q==,type:str]
    SECRET_AUTHELIA_DB_PASSWORD: ENC[AES256_GCM,data:MbbJrBDWgkgId8hWtVAjoMJYdI2zXXvS,iv:cDemkGjqRyTZU/X7HLjFLjtwxFp26ytyR92analxNm8=,tag:KcEP3QoGPEpUK3WttGQnmg==,type:str]
    SECRET_CIFS_SHARE: ENC[AES256_GCM,data:zQiMHddf50E01Sh3lAw6g1j76XBqwDFnVGg7QHq+/f/3/2g=,iv:2VKmejD8tAfNUrYhfRjClEmpCRYdL26WIKdBGz9KpoM=,tag:+Bq0lOiVp0oB0epUCL/erA==,type:str]
    SECRET_FIREFLYIII_DB_PASSWORD: ENC[AES256_GCM,data:RP2JUlrs1UO0YIlxJXVig62a,iv:x/JvTKJ5+MfoNIE35nm8/MRoZ7+Iclvmd5pDlsVVlsM=,tag:gaPSPcQ1GDVtkYyNewXeAA==,type:str]
    SECRET_FIREFLYIII_CRON_TOKEN: ENC[AES256_GCM,data:waE0SrTEFLuJlYiIV3UZq67FLTfxvVbvSZG1bYY76m8=,iv:qBLzcM0/DbzCmznK2WYu6qHEL0EYOoquhxPqxia/BvU=,tag:UdTSk0tPPrYWjz54r+l/Ng==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:KU5CPBb817bKXDjUdg65XPo0PgWb7ynX,iv:pxLuLmHNC9SYlg8Hm1/62CGT/xNVk3dFHBFq+ufXmy4=,tag:dKcwWed4XTgUO89rDwMuDA==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:Ry9DGDgptwcAG4Za+Xmi2fFF/dfCvD6rYf2d4u0Q9gg=,iv:+SRJ18ndlyO+pnWOUSP3pfGjGsGktOXevbtjGex5t38=,tag:tnuCgS3wRaTlTDWkKPsDWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-19T16:31:03Z"
    mac: ENC[AES256_GCM,data:fKu2kqUE1Qp98EZxSNUlCy68fnbUTJoLMtVbLbXT0Z7jBl3Pwlr/sNzH+aDxaIw0H+Q4zyeLxGKJcvGpYko6fPmQHaz3RDheE7CrckVWD7Q+jF/b8JJSIyvKbbMvyvk1ju0mGvqJBc4usl5rr5xDR8qCPr1nr4vB/YPLU2/yB5g=,iv:BJBpGGI13JU30HfIGkQ65lupi7j7RlfVVrtcyEla1/c=,tag:suy1Z4czsIAI5HnUjkRQbA==,type:str]
    pgp:
        - created_at: "2022-09-19T16:31:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ//UV2zcTr2t9ebBAZCTlDOaAiBtGh43DjlWzxHpq6RujMm
            IslvQ4jCeoHAYYIgfVPD+TGYEHNNy9nvSb+wAwhaflTdPg6xiKJR3JOqEPp0XNWW
            AkE/RPA559gg4vHytYTS7KngKXhtR9GKuw7Hc5hbmg6rRV74tZVF1im9nbRhxMpS
            CQ80/fjKgC+TNnl6hjnO2ZeewlRCVTt7pmgaBtJvlcUiVBIrLyGLPjBzjFrTexfG
            B89XR1jDZmGe9kQGo/C29mjOwR72LpIwF0oGt9HmdFaThkcg8i/cost81dpQ291R
            ZHlxyxYqFIYorTAw6LqreSg5X1HcqgkDdz8uBJCcQeQ198dqYE9IjB2H7imdZAkK
            ko5J/O6D/dw9tDkWEOllfh7FiFUPkByU36NmVTmqNJgZ+mj7hY/0ZSWteN28Bc4d
            2BXg6BhBf412aEWhep0PKP0cNxmI6OjS83I3lz7iKRBZu1DOyabMENFsQUyHCx28
            PwGLqdDnpnL35xgRIINcdhwYimM45R4U77PvP/s6u6nr/Iovj6Cc8FBojs40Qhy2
            tqiWXAcAhkoKB8Uow2VRZXt84jCwY5pfEMVpxoamHC4+8nJ0Ao8xxtfPNmgH5dPH
            I+QJZdT8KATQ7+4Fmpt9U3ghCC5pHtIwfdvl+avPHr3Drsg4S/4EGK1uZ7XlsS3S
            XgHwjaXsUKqQliPEUpeip5/vxqaZtxvYa+ptqNFnk7wm+CFKEmVx77Pqu+NGmd+5
            xHlM+GDxt0U/CV5Xy/XlhvsjIJQOo/iF8dSEJHv8PQKXXllTj9HU+kGGqfcdGWQ=
            =IUGg
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2022-09-19T16:31:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3cpxTiGWvJJAQ/9EDOdsm2+XzYMg7NnEvMkSNIKe7n1nsJnuDvSYbpIr7a+
            JcDsBa8tE17x51j2eOrLYa/ib0kwV5rvbg5NRK06bfpq+dqKrleNY1YfJdwdKCPb
            gH4cHpCv4q+QiFYPp/rFTPBmXdYe2nLRnkEZ/B4LgZrvbPZTP6bo+D19J/uPb/47
            v034kXwVmLBxIuyldjM4d+11BE5CwITNlAEHtvY9B5JCvRKoifC6H8tvKwh5oFLy
            idcTWWHIjLpnwSF3Ri2/ZM9jUyNpPFD4yL0tjEmRWyVDQimp/jJQGdemACBOomnW
            YsYsiffzQA7OIOKQc/0Jtws1AfqkDQk1YMpIJlgOePaFOZ/RCuVcJXdE+4EK7Ul+
            pImqZLoa1JVupwSg1G614xRksEhhFK+UmUE7R6UA2/9fhrRPG9KXjx2PRk9QAMnO
            vvtRPeAISO476zV68Mr8+gebW4nCM2v/FF9MSIjTUWEnfU07MeAZsAUvE4hlBgZt
            vgOjo0JXBrLw4gFhu4K5QoO2skrFayOCGLnzS+eDs2aurVAkOdSIaO/cj72Wo4EU
            kY0l8PDjvDLF7QUR626XZPRZTZ5McbxJyTMJ4BVsh2I9pbD7gc0lNr9Hsv9uV/H9
            IZEy0bDaJH5c8q/h9LG6IpTmL4W4cG9eOAug4s5TzJCcJ71rV+sAIRm8/+ljX6zS
            XgF9Dhp3obXtEJR58V35zMT52ZxTwolN6X7N5EJevecTvFbzDLWhV777MavDDreC
            40NEzslu/KZOTRibfGIMLHlO76T5NASE6zvfdIl60vSGR5/wUtc/kj2SpOmhTQE=
            =n7QX
            -----END PGP MESSAGE-----
          fp: 8D200BE9B98597BE5D53AC63586602C2843240C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
