apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-prometheus-servicemonitor
  namespace: networking
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
