---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway-vpn
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 5.6.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1
    DNS: ${POD_GATEWAY_VPN_VXLAN}.1
    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.31.1
        env:
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        envFrom:
        - secretRef:
            name: pod-gateway-vpn-secrets
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    routed_namespaces:
      - vpn
    settings:
      VXLAN_IP_NETWORK: ${POD_GATEWAY_VPN_VXLAN}
      VPN_INTERFACE: tun0
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "1194"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR}"
      VPN_LOCAL_CIDRS: "${POD_GATEWAY_VPN_VXLAN}.0/24 ${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR}"
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.6.0
      namespaceSelector:
        type: label
        label: vpn-routed
