apiVersion: v1
kind: Secret
metadata:
    name: pod-gateway-vpn-secrets
    namespace: networking
stringData:
    VPN_AUTH: ENC[AES256_GCM,data:EiG6CMYbuNGkf6ByVUvpQFTZfHXE/viexYa1eUHD81bdjoMi0yC3Uf2v9wk6FBggGg==,iv:zKXYDrBdN9OOThhsFGyjwjqNqzQkpHsjtVMSNP2t7/8=,tag:Gn+7CZTAZD65qkT61MAxJg==,type:str]
    vpnConfigfile: ENC[AES256_GCM,data:FTb/xj9prUYx3yDGe5QFHFXl/JDGtqqD5lmpdqz3+tvzKsF56lajxwuksz7Cg+AJuOWFIGWhq4ndFUoQffuXslCywDGkuLqA1rsVxbvNSsjeuWZpsgwa82dyabYS6SLCCw1fJAGTuRJqrK7iOGNc3P+vtsNUdKW8lwtvhwGp2Qa2xe5DI6SiaItru9iDVIXTJUi3I71V0jcyYY+mfOVVQgEXNUb49S039keraNI7UiyOYSVC4qVV8WRSZurpPkN99770ltbqmRo/NzZeEBanGcuk71F3MQ7rnszmlC3mPybwX2FY2sTCuDmjOlkFj1py38VPqLoYiI6WficUuejLeDd3OdcMvyMrX6qRRtgea6CodFwuCbgt+fG72xXaY8KhEmQzznzjfxrh8A5g731w3b/bJp34Qz2bzCOyhyhl76P3RhlBvBiitsP4lRB0obmdGMerEv1wZcltRhKWPhyQIZ3b/ryJ9WU9gsqqbX0ZSO6eEsHNSzkp8Y6p0R29DEUyLXs96Aak3oyi3clUNaj7YgeoSeEMTYuV+WsOr32XTi6Ykv2BhRtm9ZyEURkpFZnRQvhunO+39Nar+u14y5NlyqGcos7/mMp6n/2qti1XfZZxWjVNpzpBRN9E1TdMTOqjmSywEDtgd3AG8p25jVq5/wCQ8nBBEtzF2aXMHm9aw1tsulX02R9M6b4lP4NYatuptvO3EJIJ0YHfK3hVyNC51QYCQYne5wyXeWoSR7Mo1mGJQAWzF+Ad895itibtDXw8Pv3ROVnHKxVg8oqJSBFITiWevKyebaExMOJd3T7aGSWahaFuKPdyWBMG4N0p00bUztfFq1SHUEKIh/A2Mr3/nr/Sh8sWihCtY2Slut/1cyRuYkSkMiVKQOxqGjhSLIE/mKVmn2GCMEfvjwOiRAOm1qfM/3MOy9098CwkkrLtIuuG/bbHCNKx/9KGr6seH6udnYSeXnWV4m2Q2B+aQa9LthStbGiWII1BfrFWOv/jf//IT+cMIyPml5kzi4jnku2xkyrsfVugS0i59tgSFA+rDpjf2DgLJlnF0XDtXdhBME/qyDv8IhxgrgC08QS8KD0sDam+T/7n9dQFodNna5eycgu3d9XoYXuqakglHKcw1dts6n7xJZOEhPgIva5L0JFpgd4kbvUfeg6deiK0THuXs4QWs5rHcdHUWcV3pu2udfp0XV8H3S42dGp/mnBEpQc/sTNmAyi6bL+k6p0EsxOaW0zdX8LiC05Or7G65KBBihvHvnOOwfzcWXGqdGnr5CW67UnexOgq7T2XN6oWidiIWkjvc+16rhT6sStND+NxhzY4vfpqHMkGRGkz8aU4WQDzZLNotQhrV9f4HvM5EkS/yemjUguja3tdD4kKhZnz23KkIv3Y5keIl9jWmywHxB+RMbGbCoxOglprx3APFzOkOXOpPw+c5I89wip1DUuDz1CD7xl1c5p76qiDlt4yE+/JiO6Wq39ukf4LmYtjygL0szTbL3ZeXiTl/i12RZDffz0A7ZjD2H4c9KaIUVHMtE2DiMn2Qe4GWebwSvbH/D+osOggc11nL3h+EkkvUn7Nrwi4MIvqEafhxglTx9GfBy7wgJWibPvVKNsLNNycOqwdIlaN6rhz3qE1E/ajY+SnjWmG77HvV0B1Fq4P0sykwEKJdnUO34gwiyKdtC5FhcsxuivJObZV6vG29pVBeLfrhdaJ041X/AidKM0tOU376KhtliegbgtqMLug2gSkYD2fz3AJ49OPMuTdVKzx9vZpJnRD86hu/iXQ0pTwShUuXdeq+fzvpPf6yZtY8tJBvieXAUnbHsTudSqAZ2O+lhC+B2YZuPp6GGTF6b8Waq6uw9jceDFr5yeW/FXxdnNY4mkZRPsxDdoGH/ziPBcZrtqJNA1FptGvdPHQsFo/HLxf0zIRW4ra5aL/L9/uw2J9YM0IzkzUZO/krwJa4s+kUUh8jLUYo/sSajWxPi6tnm1/ezZACSZ2quWgxYVS11tnujEILbOcKm5EFeM8SQept+zkQ4VkYDi3/TVeH6kBbzLQcm/n/at382KmepPicaj8+2mtNbp+QbCenBbMPwZWtHNn49b210vGkH5GjG3qcNxqkORYj7EERgci7yZ+jwyE34V+2LVZsT7EEAyHc/DPyPGRgLeJxksOOZA4fuGZuVjftZbsbhclaB9b1I+amE78ErjL2yz9XEyJEtl9CG6gWcM+HA1vzmgFOfpvrViil5Kq0yqAh+wc2z+SOWvs9xlHbWVVXGemiTKpJ6GrA2ULpClsoOtBI+Zk0wkuzf/r484KgrRpdE4bghMdJpef9dP1t4UgTANspbIrglqjio+a6hHLFG7wHVMp6QTCYKL2mcqIdZVSmNFag3oXf2lnXvgdZg1vaQHeu3/v81UPOZzzOMWo3gVpWKG2T6ug4rV5P68GdmL7k/iqwpVGUQQaJLz744FeQqPFz/JattIlsMyLH2M8H1NXlNbDbd/zq5P/CZFYyMTZECtlILvAbQQVziV5wsKNkHPITLuMllGW3vjlmjZeAmY8/1mG7vLEfl2tALgwNsDc3EvBAaNOfpQ5UaSEFJbiVRf5euUjryh+pITMsdnBE6bDKT8rB9JVe2Yzq5XbYHkX0XVih7G6HWZPUFOw1O9dQcsQoK+OvxDFl7iLnlbzKZ3MgQZ2uGaU+ovZM/kFhQ4zXNjT1QAUUGL9xrHj6O4EXAdWJ6fM0BvVkH5nQiwcyHf1razTWwx6CHQ5t8T0a9c5USRBSjA2Vgd+uAvsNqzp8FVk8NIB91MPat0eVnCbXYuusCTu55xg9gIfINHYHYXdaPvfH0pO/V3WkM7QhtiI66ubp3OmE7NYLotKKmMrFKaRiW3W/v2fqWH4G3L9cqQR46tk74ZYpBuEBHXsPAiPuP3FPdOlAjrdfaiVCk/75pBJx+8Lp7vMvWwQejazY87BfEBzfrYL+4ckfaPiVUD3fJAaIKtgtEgGN1VjX/zqzDE73JDBlAnfnhkQahKcKwiAoXzJyJJHxj4sWN1l20LkZ2wsAEBkJJobXUBaPSV81Soj7YQ/k85x3OygRC+moASSUoTSPe8jwicKDfgmzJcFQqLEuQ4bPVu8T32TsBjDigttL+Cyh4pqJpgSe7SKMo1Rbat7PwnlXNOiNmz8YUsQVA1E9selGX/ey8UsHLZM//Np4cJ2nyeIxq4pFtaHUtpvReRhC+dJ1Ffmx55J/Fag/sGiZIYVEx6vd3tNtKURoAPsCbhyhyS7LM6s0Gzv4QwpVvoXIEMcorygSPxLiAafo1D7VwWSD91TcmLNZNr1KE8ZR1FLvoPg0XJjSPE9+mXVVxtTysCs8VRq+4EKSWIj0w0E8zz1P+Y0gPKKQgtL0VNfoJvgMHgMJAq40dGRtAIGc7HM3e5BkDhxtKM6RPV/1WUK0x3pMyP38yZUJX/jWrq8VWGA+fkLIHP2LjXlJuhXVC+uu/ffIeOa4hBFxWm8MD4E3voexfEKdGq6Xd8lbJdFeClhS8CWgtDVwOwPyWHq90TvfvIG3CRwhqI48vDKiferLd3MwDsz9SlVd7Snb04S3UQaCcwCs3Vx3HqzvvWYzzK/QvVPGzjxr35GAfL7z7YGB4Xc6jFRXs6kwIkTc29kO/gG++zRLfO5USpeO2tQqIYx4Ny/3zSm1EA2C/QDpJPOujrLyZNvuRSWXEphI4U/zYMrFuiQsQ3E4eK8+0nj9tXWb0PO3eXY78aEchYQ/els4nmc+NpairAhh4JZ2ugVfqAcrHYOOgnz8k/lbgv+6RLYWWpaQcgB4BFI+w==,iv:OiWHXw1os0IgwUEJSyA1nOUwKBUDHycAILztk4uNh7o=,tag:4f6OSK+w88EX1hpeWNEr/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-06T13:49:37Z"
    mac: ENC[AES256_GCM,data:rPWjSXnzCHO+PqEHo8gD8LduETZurqCvMjG/H9vSd2ZgGo0Z0IE/S76uVN+vst0DVkLj6fWNTLKmGg57nnTUKs2xdY2/bBvCf6Zog8InEqxTTqqHsIBlZ9ctgkoHNnhlohuiqRV1oNNuxDPN27xXwvIyqMYOwG7jCOWpr7aRkt4=,iv:H1xvrSpxlYX7x8MlLg/GvvIH1TbqkiQu/658B8t6f7o=,tag:AMyiPt9rr2dICTOok/dvNA==,type:str]
    pgp:
        - created_at: "2022-05-12T19:07:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ//aiBHKBnItBhcHjK6TPme/+6e6Y9zQzakn8N/mIQpzu8s
            PmkECisgsspG58sI2N4luAB70BBCmYOCPTrXHHdXjMWS+V7sk6VbjJNWSnjS/lTh
            /CWKnQvvy52MfG6qGy5E3ciLfwyzDqHe/RkF22F8hybwmsHfftRTeEYanTc8WZl4
            BhvQmTqh36vGuGgIGPQXhRw8jDv76CeSQ/EQBoxe7MbEPCbGgs175ZwxKlP2k0KA
            5OOE+0IsWR1HlR2MH7NjrswYHZ6XZyn+CN8LXzIycCRGFMNLIiHqeMSi40w4BgtK
            01W1YVi9P+SmJbF1dVOaebxaqsvAz5Py2Va7iNQ9x0eRO2oaljpci0CgJEYdk239
            4r85iRmn17w5lZvjZCnaioQBap33fLRSiClOh5Wm8Te8uDVWxPa23i99yPaJX++9
            rIQ+/TsrGSeZwNvYdt9jeiwKpjxHnoDfBSXSNTxpGqb4aJAxmbMtlo6rDa6ECCAV
            1pC3nV2+2HRkQ1hiEwghx6FR8qKmlgPqn7xSWVTw+/CePgeeKC32rgxAoSW0LCcc
            jHSJTUtw92B7fekiWjw8seyzEKpyZJWK+J8ByD9lizTiW++sdKdh98ca9QpU9QTC
            KLs8RMHfkXEe6kppPy9WBA6pI10yuLvG7WgZFdGkKScRrUpPAL2a/qInvsKTCpXS
            XAFuxLXUfesxoeILLvZJcGVoKvfpRWNJB4CNmOXbeEm98qYsVFQnHjg6GlZdD4N1
            Tq+LU32jUuCRsu7RV2gYMmxcmbKsBFNfCxpe/I/yl7eQSC1ysWSeWeQyKtZj
            =Jxnv
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2022-05-12T19:07:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3cpxTiGWvJJAQ//b0H1uPxc0YoFdnpUElJHuqcfc9VV+KlQsTTTYBeh/aVm
            GJvJC7QmFcb06Hf1646e3itLk6VT+u7L6++62aApcnW0pVdTODNF6WLf1BOoyRuF
            qxgVrvQ4vT0VqlS0VugGlpg1Jqg9VOa2rM550kRhcGwAl/bbLqkjmLjfCGw1iKtH
            SG6OpTnqcr8YpZ9O6m3J9GO9peumd1viWEFf6lnprKyrQwGQxHpft8czdbvoVZtV
            2k+j3PE5TyE9/eJC7x+mOHq9Uz3+/k8mpxX41cT/hZ5ATSJ73mzjRkLbMGOp3626
            VwAYEx40VaR92/X2gGRZsG0wWbCOgJ/lXWpW+HV/fKZNjhi+xN1wAavT5oyo/naU
            Rl9ZovxyO0wf1idJPstGlqvMi49u2Sh9PjuofNU51/vNBnB5fviSTjikTEZZ8fuV
            Gv9czIhWxchFXLlrCunzmB+dJqoMPKoeGQIy1vIEriyo1XchsxqGNyfZU51pvdPn
            8bc5x8Av4xBgdjQpNps0y8QycfNz8Y7BJscbWjv7BmW6mJ233npj7/Of3MGM2UCV
            1mhwkX70+XwSAqEJHvImma5fysH1qV9RktAOYLA7EsUMvUJ23uzOhrJ+Ykr2b/9k
            XHy3UEYUdE/zsjmg5mODVYixQfao6GCK+NAfuDfoiNYYfqSTh0g83YZo+6QI/LrS
            XAGOsRqCSt3ufUEG/ZW98hwg+/Th4CR4pkZT4NilxanfAgkY2m+j7J3DWerPn9O9
            2XnPs2oItbl20K4xB9hz6oIZO7zEhy62H0L3/4p331SlNcd4ee+cxn2eqR/A
            =m+bd
            -----END PGP MESSAGE-----
          fp: 8D200BE9B98597BE5D53AC63586602C2843240C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
