apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: selfhosted
spec:
  releaseName: vaultwarden
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.22.2
    env:
      DATABASE_URL: postgresql://vaultwarden:${SECRET_VAULTWARDEN_DB_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
      DATA_FOLDER: "config"
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: 'https://bw.${SECRET_DOMAIN}'
      ADMIN_TOKEN:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: adminToken
      YUBICO_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeyClientID
      YUBICO_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeySecretKey
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: bw.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - bw.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    postgresql:
      enabled: true
      postgresqlUsername: vaultwarden
      postgresqlPassword: ${SECRET_VAULTWARDEN_DB_PASSWORD}
      postgresqlDatabase: vaultwarden
      persistence:
        enabled: true
        existingClaim: vaultwarden-postgresql
