apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: selfhosted
spec:
  releaseName: vaultwarden
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.25.2
    env:
      DATABASE_URL: postgresql://vaultwarden:${SECRET_VAULTWARDEN_DB_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
      DATA_FOLDER: "config"
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: 'https://bw.${SECRET_DOMAIN}'
      # ADMIN_TOKEN:
      #   valueFrom:
      #     secretKeyRef:
      #       name: vaultwarden-secrets
      #       key: adminToken
      YUBICO_CLIENT_ID:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeyClientID
      YUBICO_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: vaultwarden-secrets
            key: yubikeySecretKey
      SMTP_HOST: mailu-front.mail.svc.cluster.local
      SMTP_FROM: bitwarden@${SECRET_DOMAIN}
      SMTP_PORT: 25
      SMTP_SSL: 'false'
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
          external-dns/is-public: "true"
        hosts:
          - host: bw.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub/negotiate
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - bw.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    postgresql:
      enabled: true
      image:
        repository: bitnami/postgresql
        tag: 11.15.0-debian-10-r28
      auth:
        username: vaultwarden
        password: ${SECRET_VAULTWARDEN_DB_PASSWORD}
        database: vaultwarden
      primary:
        persistence:
          enabled: true
          existingClaim: vaultwarden-postgresql
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
