---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio1
  namespace: default
spec:
  rules:
  - host: minio1.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: selfhosted
spec:
  rules:
  - host: minio-console.${SECRET_DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: console
            port:
              number: 9443
