---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.12.0
      sourceRef:
        kind: HelmRepository
        name: kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: weaveworks/kured
      tag: 1.9.1
    updateStrategy: RollingUpdate
    # Configured for Monitoring only, no automated reboots
    configuration:
      prometheusUrl: "kube-prometheus-stack-prometheus.monitoring.svc.cluster.local"
      alertFilterRegexp: "^HostRequiresReboot$" #",^Watchdog$"
      rebootCommand: "echo reboot" #"/usr/bin/systemctl reboot"
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    metrics:
      create: true
