---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.14.2
      sourceRef:
        kind: HelmRepository
        name: kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: weaveworks/kured
      tag: 1.9.2
    updateStrategy: RollingUpdate
    configuration:
      prometheusUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
      alertFilterRegexp: "^(HostRequiresReboot)$" #"^(HostRequiresReboot|Watchdog)$"
      alertFiringOnly: true
      rebootCommand: "echo reboot" #"/usr/bin/systemctl reboot"
      lockReleaseDelay: 30m
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    metrics:
      create: true
