---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 2.10.1
      sourceRef:
        kind: HelmRepository
        name: kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      prometheusUrl: "kube-prometheus-stack-prometheus.monitoring.svc.cluster.local"
      alertFilterRegexp: "^RebootRequired$" #",^Watchdog$"
      rebootCommand: "echo reboot" #"/usr/bin/systemctl reboot"
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
    metrics:
      create: true
