---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-controller
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: omada-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: mbentley/omada-controller
      tag: "4.4"

    env:
      MANAGE_HTTP_PORT: 8088
      MANAGE_HTTPS_PORT: 8043
      PORTAL_HTTP_PORT: 8088
      PORTAL_HTTPS_PORT: 8843
      SHOW_SERVER_LOGS: true
      SHOW_MONGODB_LOGS: true

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "https"
          nginx.ingress.kubernetes.io/proxy-redirect-from: "$scheme://$host:8043/login"
          nginx.ingress.kubernetes.io/proxy-redirect-to: "$scheme://$host/login"
          nginx.ingress.kubernetes.io/upstream-vhost: "$host:8043"
        hosts:
          - host: "omada.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "omada.${SECRET_DOMAIN}"

    service:
      main:
        enabled: true
      controller-tcp:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${LB_IP_OMADA_SVC}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: omada-controller
        ports:
          mgmt-https:
            enabled: true
            port: 8043
            protocol: TCP
            targetPort: 8043
          mgmt-http:
            enabled: true
            port: 8088
            protocol: TCP
            targetPort: 8088
          portal-https:
            enabled: true
            port: 8843
            protocol: TCP
            targetPort: 8843
          controller-searching: # not needed
            enabled: true
            port: 27002
            protocol: TCP
            targetPort: 27002
          eap-management:
            enabled: true
            port: 29811
            protocol: TCP
            targetPort: 29811
          eap-adoption:
            enabled: true
            port: 29812
            protocol: TCP
            targetPort: 29812
          eap-upgrading:
            enabled: true
            port: 29813
            protocol: TCP
            targetPort: 29813
      controller-udp:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${LB_IP_OMADA_SVC}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: omada-controller
        ports:
          controller-discovery: # not needed
            enabled: true
            port: 27001
            protocol: UDP
            targetPort: 27001
          eap-discovery:
            enabled: true
            port: 29810
            protocol: UDP
            targetPort: 29810

    persistence:
      data:
        enabled: true
        mountPath: /opt/tplink/EAPController/data
        existingClaim: omada-data
