apiVersion: v1
kind: Secret
metadata:
    name: smb-secrets
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:F8hXfB6bXA==,iv:OevI90vFU7g5adBTSSAnbqJPNeAryfa8KEHhg2zTaqY=,tag:wvfjq8ojmsLyp3yetszcUg==,type:str]
    password: ENC[AES256_GCM,data:7AMowg1Sno2C79GC8p68yQ==,iv:+oWcCRczXsN5YIeehC1OX1Gb11+07GkLuUNA4XXgEmQ=,tag:nhrmfD3HQktCFNRrnRrU4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-13T17:28:07Z"
    mac: ENC[AES256_GCM,data:0PHqEICrdMGY++yQth4l2cV/x1kOatoMgnavkUxeO3aTBqM/+dbQGCtaCukO1fm7bjJnO2YyLbdZW6FOaVOptJ5Gk5brfFLOLBS1xJYOnChPONynVT/D4qe0Ad2bvi99K9+JXV686wOaNBZItYVmoDUbkSj0wBY+oJ92YlvPj48=,iv:Ck8XPRgaGxtSDA2kZUHpyDQClS7NSNSs3v7ZyvkZtDg=,tag:ftdUaY1EomNqO3vJCggJaw==,type:str]
    pgp:
        - created_at: "2022-04-13T17:28:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ/+Old1iJkseTRj1T39FsQVPW+++FU6rI/ZJNsv/jkNcJi8
            Pkr/z1L7YUMQngkjVU9NQCw6xHeO2I8hWE/6uah8/XLg1yy6j9y5EEkI8jVEdN0n
            JEPZscsmup9uV7BxfmE3AojK7afVueFUujBj+Q/TlG0VspGTAm43d8uJ6hDl791F
            YTiNhNEsOEDWWdh+0xG/saO/SqkFxgn/j4N/Pbbrpl6I0dHvRV5q4tgBnD9nqCnI
            DDC5pRU4OrRQRLC15rJBZNhyozTg0GtgkeC50IcFHoawS5WrjojEZypDq4C8xv2n
            Ll+3X6C+2yKwpaOdZIP2nYS4B0vVHd54SgBIzdOh2d69nScwCDN0nf5+dNunJLLm
            OK4lZ1iWv05Rps0pM7UelpeQaqCixoWy6O9OcFUrq0GiwbXR5eq6d+KaPqnvwpqZ
            bDpT7CEJTVbZwK2iUzdFxbRYC0WNNdD1D5nSitiCC8Bgqfx1UumUaPhgi8eYr9IG
            Cl4QDs+0cPbBa8pjXKd1btZu/S7B1se8nGmEISaNDhQ55HsereMy3mTP7kDkxUbN
            4kz2CDNATcWYsv1n0gqvBU/v8oRIEKBSdwjMF9Y/vusEoF9qZjQVMQXqiC3vqrKd
            UtnDnrydekft4eWxnAcKmVO+cbk/1XRMaLLYXvLAt0Kj0WnQRlGEvSRIwAaJEiLS
            XAGtotPb9MLOshSvrg6NQrVzmoQWzUXJM5JzRb2+XMTay5fvFDIMBD7F++0MMaG4
            QNxWy9SJUyZQB8vmyVgfLksiOS+ZzeOxyzzYGwIPKVgGRW3BypPxmwGwdchn
            =TCg5
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2022-04-13T17:28:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3cpxTiGWvJJAQ//YNGS7jnFDa4E29PEwXyB9qvnBEW2jLqNaFvKBJDc1sxi
            CoV7nEbRWPyB83Qrjtqs7HJmliMSj/gejGos5TESxidstT8sEBj8ze7dvYDNu+pn
            /J1o9VZ2y1BE3dHoVESDhrGzMaw/NU63xG6RUJcil8ut3EYLEw767BcCyJK1Z+WM
            BuWimOhU6xu8sUDgBbuSKLy1LVbXMI7QSNVMA9QwAZlm4zxXft/6ri97pX57CZQe
            hcuw/OLGR9oQzqs6t2K9ApKrz8UyNTLihDXpvl/FPdJkBTIM/gQ/FYUAdGSikjQI
            ZH2CchN/0JwB4I/N3JpPwMRmvEwGYq2CsUlRvuzKUfPAB25BqTe9hXMpkCyBxwzu
            TgM3fnZyADLj6ZCY7i1Fh+C1faL0kFN5Dexkvwh3+1qyFBDELkF0CSMkW7yA2QGB
            l/1YTdRbmUa9hesxr8ti3P7nUMvdEHUM3pnxSZQcmB2aeJbZi9I74AzN729eO7/i
            RypPhwAg90L8ZUObnmMKZ7GL4vAXoCiBhSh8zFp0XaNRVgT+2aLADqs1Lc9+byYi
            Kq7/DuMEVlqegBmouKeDo9UWaPGy+V6fPdNv5aPK3Qn1gVqTheLQ/DBtD1umgOh3
            v6uskXfDmHA98v03C0Rl35uHydmNw1fk3ciOzAz8M8ctsIpsAKqPFiAJcwSL/TXS
            XAGvQ2fTptIMnfIyhFUMirz0Akw41IFfmADGqyZ1WZEWi2VzcmshtaXHVtfoKWrg
            8S2jwlN9KVfnZt4aQ+UATVA2fwe0Yn/IT+/Nzhm/5HYR0eUH/6irEFi+QvhK
            =UvrL
            -----END PGP MESSAGE-----
          fp: 8D200BE9B98597BE5D53AC63586602C2843240C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
