apiVersion: v1
kind: Secret
metadata:
    name: console-secret
    namespace: default
stringData:
    CONSOLE_PBKDF_PASSPHRASE: ENC[AES256_GCM,data:OHK3aEcnEIeF3S/qKkCtEQ==,iv:SU8cqbHrst+3lgMKSCqbHAEf+rHAgFdcc/kbD6kJeUQ=,tag:aUsLOxqteZmoEa6htnSIww==,type:str]
    CONSOLE_PBKDF_SALT: ENC[AES256_GCM,data:pu27MvFnVw5zgsd7cMAeKA==,iv:qP25tispaX+IdtBjN21rU+pbfEu01IQ+KNTV06Azz+Q=,tag:4dLM3r6ncRi5FOyI5kN27Q==,type:str]
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:lsmO9XeC+gdm9YzO03pewA==,iv:qtKsVUtfe1KBrf0rjQ7tqkBnwawCXxXRXR1IK/HWsIE=,tag:cFA0xnsVlcF5shil9n6alw==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:Ibl8B9UsiXNb1sjFjasAxw==,iv:X+vdPcJcU2SVB/qfK77K3YzZa26ivdcq19N0Pj2wPw8=,tag:5eg6PVNux9deok487Rlb0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-07T17:37:39Z"
    mac: ENC[AES256_GCM,data:oCSBXmiIV69Az55l2F7tFPRCEp+XHilOC9YtFY+kmVtlLENCQEWjZa3eNvBhKbpa1kI0tKOg0LgpTHJTFqsIJ5oNhgnwfeyahyRNepVFUZcqE3ZgtIoCIin697pvckka1W17w7dAxTByoAlkdx9Axv+Doik+5V2J006fIEac2WM=,iv:i1cofLG/uLB2zleSpt0v99q8E6l/pRsvNJRhriHgilY=,tag:D2Cc91+fQSpLV5kZ0mFi0Q==,type:str]
    pgp:
        - created_at: "2022-03-07T17:37:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63ARAAkELK/qN67hZwXgNOq7huimr8DNuqMHS6lbSh6OmnYNDD
            +FhhpqXN20VwdqYF6rhHvBmhG5RFTQ01R57fFdz65im3VOhGVJ6/NfaWHs4nM0rx
            h5YApPj9gayzi1kp1KWbQz44Nx3DFFS1Gu12e17hKWdn3eMq2uNghWpVjG7POxQz
            dVn+oiDmbCZoB6bYAZ0BtX6SLeEUdn0iumc3s35aDt+le5Ta0wnDAMTQ9NBgj/sU
            D9kCcuN2LegJqroKAy4nAIAL/nnwGFZ5StW7u572Ll6w7Crg20p1kFz+dR1L9ND+
            WevUp4uqFeVHzit1TD6bF+yFyrhnxiA03c5Ird6Q3iQqRwuxbBF9Ex27AnZEgY/1
            f00Kk8GTN8a+Uu8XhJDlsHyk96uUsLrIOuYHz00kkoqfFt+c/6fAnOxkmnhk4E3K
            UUTXwPUeYWorBnf1reRValcRRM9WqXZtJLUPLx5ATfgpBEBtvYTHzab3luWgBwQ3
            dTMS5lWdxP87SG16E9Lzzu2MBfuzfHhAiVECzgTe7o7/XskVnfz/+Ct/cLlnzOIF
            Gam9XXk/UF3rRZMSIwGU9QZ22E4B2XrMeKtpqusQNVX71tDL87DkJGaIcpOSpS5E
            x0VRJtU6vFUUfevj+dTS9waC5rAEE9QLgIDkr/wB4VmwfPtjBZne/gCdYd0IxrbS
            XgHUb2FEI3stoxguHTJEaLV/WYB1pE7w7kwIPX+ABxPFVnKcjUUzmJdBea9JXMTk
            xi2r0WZmbRQ1DPT8O1hoAtmgHenkcrGQVD6I1685XSGCD9dCG7u2WFE/Kbi8mCM=
            =zWzH
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2022-03-07T17:37:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3cpxTiGWvJJARAAgU0i9fYo8h1aG30I9EQ5o8XC+chdUakAM2vmnMNSbkfG
            2Yy6ZW6adWnB9bAjo8vh0y57tbxyUVP2w3OM+hgZ6QYk4p2clOLAPF0XDQ6w+XWD
            HaaXSfaneYBAozcosP107nMdlVBzMLeeyTAEkTp0AGyve7p4vDeF1JV7c66Np84a
            p18l9kNujDWXubcdsuaw9qfIYeiktAyJr+xnyu7s4cjxJYwA1CWlJ5575GMUiujA
            QOlPWoIK0zwLTHcV/T808fCI95Os0oWsxj1X9QZOUzjN4lwwIj4Qd6JVeN3vxvuG
            MuFK4telX9p456tOa16ar+AHAqGy+/UVnmBGwvwgQGLi5zzT4TdHNSP1/Zcr8FpQ
            muNFOKhU1WHVAYSPG8sAATNmTuubLVZS15RJKg62X4ebq5jmDJ/g2H2Lh0RzOgbn
            2olj8F3vRFJ+44DH8yoaJTizvfUlhSOc40Fj6Wx8nZ9zlLTPurgV40TqqwmMKOd6
            Amg0jGMKBNYI/7E2WA5UMri3xyzBV4P550eaKI5yU92VRgi8hj4yuRucOmDTU7mY
            GUeR/z1IOw1HvgVy1rZPeVNBvsm6L1N4aOyCj0UyhzxJpf3nBum6ChWNhvz4bimu
            fk0WBW0QDNgztqpGk3AwSjEw9sTH00RJvl/AAGE9BvDDsddx+dzs+CqfBq62bnrS
            XgEZ5ifv1IU6QEJYG5Nal/blwaOHOwReMKqYoImcQd381CYRFg11HavyCB+5Mwqk
            YAP2QpeW8+EiTwrqLXigzpa1URhXw9nyoMwie9Dt9Ugvbk2x0QdDY2JrmTm3im0=
            =p3ka
            -----END PGP MESSAGE-----
          fp: 8D200BE9B98597BE5D53AC63586602C2843240C2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
