---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobs:
        enable: true
        jobList: '[
          { 
            "name":"snap", 
            "task":"snapshot", 
            "cron":"0 * * * *", 
            "retain":24
          },
          {
            "name":"backup", 
            "task":"backup", 
            "cron":"0 2 * * *", 
            "retain":1
          }
        ]'
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      host: longhorn.${SECRET_DOMAIN}
    defaultSettings:
      backupTarget: s3://k3slonghorn@s3.eu-central-003.backblazeb2.com/
      backupTargetCredentialSecret: longhorn-system-secrets