kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  recurringJobs: '[
    {
      "name":"snap",
      "task":"snapshot",
      "cron":"0 * * * *",
      "retain":1
    },
    {
      "name":"backup",
      "task":"backup",
      "cron":"0 */6 * * *",
      "retain":1,
    }
  ]'
