---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/mailu/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      # # renovate: registryUrl=https://roobre.github.io/mailu-helm-charts
      # chart: mailu
      # version: 0.2.1
      # sourceRef:
      #   kind: HelmRepository
      #   name: mailu-charts
      #   namespace: flux-system
      interval: 5m
  values:
    certmanager:
      issuerName: letsencrypt-production
    domain: "${SECRET_DOMAIN}"
    hostnames:
      - "mail.${SECRET_DOMAIN}"
    initialAccount:
      domain: "${SECRET_DOMAIN}"
      username: postmaster
      password: "${SECRET_MAILU_POSTMASTER_PASSWORD}"
    secretKey: "${SECRET_MAILU_SECRET_KEY}"
    subnet: ${NETWORK_K8S_CIDR}
    logLevel: INFO
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      hosts:
        - "mail.${SECRET_DOMAIN}"
      tls:
        hosts:
          - "mail.${SECRET_DOMAIN}"
    persistence:
      size: 1Gi
      accessMode: ReadWriteMany
    front:
      controller:
        kind: Deployment
      #   kind: DaemonSet
      # externalService:
      #   enabled: true
      #   type: LoadBalancer
      #   externalTrafficPolicy: Local
      #   loadBalancerIP: 192.168.1.211
      #   pop3:
      #     pop3: false
      #     pop3s: true
      #   imap:
      #     imap: false
      #     imaps: true
      #   smtp:
      #     smtp: true
      #     smtps: true
      #     submission: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Deployment
              name: mailu-front
            patch:
              - op: add
                path: /spec/template/spec/hostname
                value: mailu-front
          # - target:
          #     kind: Service
          #     name: mailu-front-ext
          #   patch:
          #     - op: add
          #       path: /spec/externalTrafficPolicy
          #       value: Local
