---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mailu.github.io/mailu-helm-charts
      chart: mailu
      version: 0.1.2
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: flux-system
      interval: 5m
  values:
    certmanager:
      issuerName: letsencrypt-production
    domain: "${SECRET_DOMAIN}"
    hostnames:
      - "mail.${SECRET_DOMAIN}"
    initialAccount:
      domain: "${SECRET_DOMAIN}"
      username: ${SECRET_MAILU_ADMIN_USER}
      password: "${SECRET_MAILU_ADMIN_PASSWORD}"
    secretKey: "${SECRET_MAILU_SECRET_KEY}"
    subnet: ${NETWORK_K8S_CIDR}
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
      hosts:
        - "mail.${SECRET_DOMAIN}"
      tls:
        hosts:
          - "mail.${SECRET_DOMAIN}"
    persistence:
      size: 1Gi
      accessMode: ReadWriteMany
    front:
      controller:
        kind: Deployment
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Deployment
              name: mailu-front
            patch:
              - op: add
                path: /spec/template/spec/hostname
                value: mailu-front
