---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      chart: mailu
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: mailu-charts
        namespace: flux-system
      interval: 5m
  values:
    # renovate: githubReleaseVar repo=mailu/mailu
    mailuVersion: 1.9.10
    database:
      type: postgresql
      roundcubeType: postgresql
      postgresql:
        host: mailu-postgresql
        database: mailu
        user: mailu
        password: ${SECRET_MAILU_DB_PASSWORD}
        roundcubeDatabase: mailu
        roundcubeUser: mailu
        roundcubePassword: ${SECRET_MAILU_DB_PASSWORD}
    certmanager:
      enabled: true
      apiVersion: cert-manager.io/v1
      issuerName: letsencrypt-production
    domain: "${SECRET_DOMAIN}"
    hostnames:
      - "mail.${SECRET_DOMAIN}"
    postmaster: ${SECRET_MAILU_ADMIN_USER}
    initialAccount:
      domain: "${SECRET_DOMAIN}"
      username: ${SECRET_MAILU_ADMIN_USER}
      password: "${SECRET_MAILU_ADMIN_PASSWORD}"
    secretKey: "${SECRET_MAILU_SECRET_KEY}"
    subnet: ${NETWORK_K8S_CLUSTER_CIDR}
    ingress:
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "${SECRET_VPN_GATEWAY_IP}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns/is-public: "true"
        nginx.ingress.kubernetes.io/whitelist-source-range: "${NETWORK_K8S_CLUSTER_CIDR}"
      hosts:
        - "mail.${SECRET_DOMAIN}"
      tls:
        hosts:
          - "mail.${SECRET_DOMAIN}"
    persistence:
      existingClaim: mailu-storage
    roundcube:
      resources:
        requests:
          cpu: 200m
        limits:
          cpu: 800m
    rspamd:
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: 2000m
          memory: 1500Mi
    front:
      controller:
        kind: Deployment
    postfix:
      image:
        repository: ghcr.io/pumba98/mailu/postfix
        tag: 1.9.21
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Deployment
              name: mailu-front
            patch:
              - op: add
                path: /spec/template/spec/hostname
                value: mailu-front
