---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-postgresql
  namespace: mail
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
