---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-storage
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
