---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: mail
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.12.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    postgresqlUsername: mailu
    postgresqlPassword: ${SECRET_MAILU_DB_PASSWORD}
    postgresqlDatabase: mailu
    persistence:
      enabled: true
      existingClaim: mailu-postgresql
