apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:nlWXc6UovhZH5f1elG1Dq1Lnlq9Us9XIZB4Y8dQFii0omo+2UVa2eIn8D8Ud/b0rNyeHlXtKgBdyiB4J09g3JSpSnkR+EhKfLyAZv2CJdVw7c8IDGzCSMtVn6RfBIiaaV5mZC20z1nX3Z5/QRyUeWfX+GwdZRdhY,iv:4hvFKiCuGex53BtsPraRfnGzkltV0NQAlKqA1+MxUQo=,tag:eXXEDZDfadfcPH3L/E1ztg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-05T19:37:02Z"
    mac: ENC[AES256_GCM,data:g/StK/mWGID0FydgTza3Juab8TYyGBZ+jpYyCZQvTNDuHFw0dPnv1tccF9+Rq0wwHhNLwUJ1aNp360Vy//VCHtAjmiwAzGgfYCmQ8KqXfYkuvleXQHn/shmL8wpsWv/g9bWzoQOPaEqaEvXSUUs16Lpia5wjDS0oxzaJXMV65FI=,iv:H1BMj1FBVhe3LMK2Vl2Tt/MmiNEOiOQ1ZX1pDecY/Yk=,tag:VuWJ0Z3DX0IVxXbrjQ9W/A==,type:str]
    pgp:
        - created_at: "2021-07-05T19:37:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ//R0OrBm2jxxjvG+LZ21l+qKZ+eUvrkAO3nNLh229U4leR
            rDACq/Vb3iGthhsmFFRRjxhEvYanFFI/Zv28kObXysjgjWlfzZwLx/S/nhe3eb3a
            htae6S3y28mq+eiTP4agTEEx9RDcr0RBqx/DqZyw7Ht4WraHcs7D4rSlxCcFuHCm
            +CzYLSl6EM+uY0mF1d5uLTdBrfb2rRofb7ljdq4x+YQmsFzT3D+yUZ9IBpPhOTIr
            6WUOM6+R74wXXGQUciYU5Aim+fDaYHB7mzZJ0k+g9yTkJLQNsOmBuOFrCxb+3qn/
            OMlcCANEH5ernqrMtkqEwHdW65IgB/3nu8yFY4rO9HNj4GU2Wg+sY4wkM5fVVNyX
            VwxqwQ5stqaxWPi64BIHC2kLHzFhovYPk+iY4DFgIrFlBAL60X72Oh0dDjxcwTUR
            DhJQDqC9Es1GRCTJj/38G3R3WNtZXfy+hTrT4a+1d/qsz7ZaYpv4gzRSO37Fecgt
            tVq4a0K3b/IG+LIqoDsiRh1biKxVqIMsY7YC+8f9ajQBTXaFEwSMGiSxszS2Giq3
            ehxo3CpmiPznkpyZ5W3o/wRsDEGI7BQpxyYk9TsU3v0bcrOaa0SimFyNH8Dh8Kp/
            RjDVt+2+NSYgwkMtA7o8ZwWsMwFcoYKf1vHdVimGTBnYkx6jmaRuY8fMzfLzovzS
            XgE5T7eRCgJc0uPEBi8vRDneUekVGzQo0gSlcO7eOOvtkOmpZT1rC1DU3GTtx3Fj
            fSJbV5R8vxFLCm6oyNFdn2VA4amIj5yfO2QizBxwtPRLDtM5ZeMjQAS8uVaftsg=
            =ddyH
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2021-07-05T19:37:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA64B9baa/LIjAQ/9Ey1AHlAqbeEPrklpSKxy4w+E0CDDQ/LqfM9jESfBlBpM
            AFuvnPGVF782AR2yxrZg5e5+9psR1YdEKAwobxE9kMSLp9/rLSncPn5MjpA8PBT2
            lyhtjP2jDOMMcW6JgkqlEMpmGexTSci//WKL/JKeqyh+0vQJziZ+6fZmfHYuEhAQ
            hgJuyqzpYPxO1lIy0A2MpFR+bxp/XdDFLgZzM44jUXAMhtQ2cnxWUlfJlvO08md5
            qjoWz4dbmcJNBdWl10mOYoPVyrOWAmtWJG65m90tSnp3y/L5TSUmE8sFn9Fhni4d
            ZSelp73+P4mSpQk46ImdDR1NNtDGaz5iP3N6HoWJN0J/LHqGb9YmLmMN6WYmQWol
            Ux5+e6yN92hyLxsEAoYz9lz42+EM8IThXw5LQUdu6i62FziI7T7wZ/VI7LZ5qs3a
            OfSvMHceKtidCr7JGQI50QLO9rBBHXmIfn7Etv/CT+rbSPG1JtNkVe+9l8xMXp58
            mJfT+IFz9rMS368LiT+y5LHP2a8iDxZZmxcBsem3qlw+L4/ECBeP+Hb/SqasBUaq
            NUG3jyqeo05fhlKWKxyUfrPIz1lkrf7TXaj4yhxd85iYWWSW7VBJWM66/2sN3rcl
            78wsH+FLalXYCTraPHgVEk/p1G7HEVJS7y8cU3IGVAaj5g5ujRdRGhpk8r63e6vS
            XgFDbG24DCJsRjICwA4WnvNWaAcKXt3xrVc5XzIkWtpRey9oV02kqAbkC6CpceWB
            9hFwqaREqspsn4VlwO5+DzIhz8U9oMlDj0VL2IFyxmEi6j7z1erEolnVywrt404=
            =IIJ2
            -----END PGP MESSAGE-----
          fp: EE1FCDA1BD7E34481E71FCBFC72AB78A7F05099D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
