# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2/9lHcDTawI9I14mzPcXsSLHJqp1ROzQOGgZSGTuMs/btBLk0a0PYaaGKszgAderB9vQi8jKTCkZNA9OTDittSmBdLucD97KUE1n7KUUX5QEzHX3KQzGlxsTdq7nvf372R3n/F0RnHf+K4DplPrcSuX+odZaGsxoany9CkLF9c4z6sGIsaZjLdhtv3yab53rE1qN4m8GbqTbDbQMFM3giOSwgk8uQlsZLDNkUpQBQ2twVhPfzLy+/iTaXtPL8S+sT130EHquDtyZ2I/aQ9AcvQJt+4FTAiPucNR6SDBifFlYyO30vw94wyrYoAfJNTrODCo4G+WJ7gU+GKeZoypISAaRoKKJqbzi/mmDX1+vEbksrpGHYp7aCRNjltMWY6VBTBq1vX3OVoh0jBxFz4Cs9Q1LKcINmBdPa9/VPqmjwJ53484yzpb1AuLm+IGDzOA2PbqJGIQ01JwQJw4KYi/w6Blu7MBP/XKCYadlIwug0UfWwgAx/5HSJJ4b9gq/iQ0rQSFGsCMb4NWqzOjAzO+UPt0gFBe8A9fwGxQujcNutrFo7XwVjitSy9MCOf3lVljH5wnN+XWu55Q1OFRtQGTYghsS5hFCkFhr2lBrQ4Osxnq2XdCWvb2f38Q2n3UPcfKbr5fz4EyMUwbQZ4D6l+fdPINcuP9mXTgM6H97RnSblXwQF0LHAAz/M+GlYKn6VNZ30XSPIrwhf4vTcmJJSc9V/W9qiHJDDbPlvRiTQg2WgvCAqc3/97eT/dozw052Y8c73VerTwHzELycFGrHkbfJ+gHEg5yqwE3XCv7ibyN7kjD2QFZaeJG3WbBmnhKhUZ2I2y1Na3/Qvwb/fbI9JvqLXKn4IqcF+Bjm1TDS6TiRWRnYxW/M4s7eFWBA52kFcvmUmSKYzzshFQIXTq9h3z7ICU+4XRIrpn+tyEIWW9ckAtq/NUTfrN4vSEyfjnVOkXjAUCsh54EFpTr5Qxx1gw6nMCUQ8qQ1/po7fQBwg5v7VorhQu0yTo2HdgNM1cwYFC5/SqTTzhwsTSd5t8W89u7ncRF2vt+OBaoJVvfP0opBGSm+Kid2P7lPVgEA0g2cxzlPEACZ83V099P26+Yo+GIt4nKwjLVBxyqP7avWjn+tBiGOfoQm22Oc650hgbO1o0u3TPpEYk7IyWzv5JX0UHMIw5dbU+yW4tvROCnk16WiswRzNLUc6rI2QhIQhkx/Cy7H5C8kNgk6PZBiRQ6ItIRnrnysY2bHIDTWpqVT3LYpXE4l5Pm90FJ6F3wvAQyJDil0A+GT/dIL6S89+imZzeoFpQl/yTss1Y05Q3YmHP/3yslH8tJSVUEOzqMHxTGNCl8MyT2e5GFQbbZ7XnHKlazQJmZbXBfgog/B+8KphKhQ20t/FXWGgSBLv4jp5SgsI1e1D+c+xKjfwAJh+z6U3MLvDIW7CxmaBS2vfXz9xzGFbgiXgt7QoSPIg2SqJ9vqFuwUkHZ2QO4E2g0ioXHI/6xJ/06eorUQ8DIKTqxGupX0Cc66OdUz3vufi/s4rAlaBEiuR1+AD8XKyzFV/T6+VKRymofT2fXqjZO51N40d0i1sehP7ZGicbUO9PC0DuGf7hHf/nhMzYWpSfrK9wKx+3ON1bubTB658FqJggTdFaz9raAJV6GZOauGgd/m9WW8HrlkZpiAH/mmTf4XqkCZ/6omLOTmwOjDHH5ignEj+68EFSraQXeue5KNpvFXu/9G5kgB8p6rH4nB0klEDQk9vyo3vup6RGsRt36a9aEA1iLfEKeGiuXnuZKkM7RczeEdLDMfz/yOq8LIwwdo+Zrl06ZRtATcdQ+nUxJZXCkLZIcC4nNmqvpSV15haZ3W5jippj1xDgTqU6x3c06beRzz36+uemNppKPEc1+BmBL1gava2w9/j9E5Gv5YfxUj19q7j7wFEcZQF80LgOCmj8npYvdccqJmdENEJz4EQfsg3LYDPG7EM2wFRpYaRZ/qS3Nt42AjwcI45C8Ucw3rztJiqZu9fydFNDJx/a8wTd/7/zRkVnlMqHBbkohiLmXdOK224xpwBQMHWIHSZ+M1dOh4a1XnbfsC89mECz4EwolIWiMY1g9koKvtUP+3DI1jmIjrISvgfg034VgLA/39eB8yedlOswFgGPEmecdT8q+1zWvFuzMummm3QkKx3jvXEkh9gOMX9x9EACGXV31BvqSV19OfFaBOjmS6XCrKJ+8QI2acVovLoxfcK5/xOcHOkHS08qmo7ZvwbrrxN9Jh2G4xzrisWjNXHLoQhn3n,iv:n4FxExQ2Ft86eJj2HwXnHm1fukIRNFQMLakUJpwUKAY=,tag:QE5Xl13lMQ9zPAMlOinGTQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ul2I1fUmVuO/BTTgvqO6/li/1cWcrZJgF/f6N63sVZKrInmQtdil6nRNHGjIEjyogB18FxCVYeR7NyQdizrrs19ey9aB+nuNSdpusNgLfIzIazBYZwNyNUslvr1m86/eVxfy9hG+EmTzrkk1rAtABVQkhpTu64yYbuJXcB/lyzkzsW4YinhF3G4tBXCz+msIkRyFVG4I5GKgDNDeaFkCxOo2qBCZ+m9A4lU1+kz1CT7MxzZZHBdSr+BPoOn7lGsmip/cjXlBdm0Bg92W5zE1vU9Fa3C9Lqax7PcxprdWDEybjAMkEVWk49+dZBiAhnIpuNMeEodRu/TMQMAgtNAdpQoRIK6iXCR3P1NgGqi3OVSvfbajt0m5HrvWwP6CrMdW7oAxyPcph/JdWOlHVzTdV5T311TLbRaImP7bdTDw20M6WML1IJSqgSP+dMc9PtUDRNebxVPwkRFLxxbKfYTCBXeYjEASgD1XLWi+sBqdjnofLacH56jnYzdxh8c=,iv:kfi/nlQIXwnz0WBFG3wRvRG1VKIBS4miKygqHUzxVDo=,tag:Yw5FFeWHL+AqrB1xKAViog==,type:str]
    known_hosts: ENC[AES256_GCM,data:H1kkn64BrzzQHGUHoyD/Z5+wxuU4DGVpAddenZRd/vc3MmMYODN2Bb3T3Z3DKbaLvcilbXa5W25fcI7n2Ih3DOMAXPPL2o897Z6ACwe4V/aXAa8JgCZWXiDq8Aiqmb18UDTuxxpJv2P3+Nj/t5tE1uP9J3mTCCEOWjkUKwyT66EgVPInMsoZlTWD6rlOXvLSAmEDXUepGe/P5v2G+rW4TWmFQcIVVugElpQLKG6HG19jfY1fhfvoebMnTOflAM928gjVxpyxL3la2rAMFhDbN2kgKgxKoX0688ku+rEgRVJjuaGZAm0yMUlqDT4STw8UX6f5Hlb2300jHqIDVmVIGjOljKxpMsNpft3JrmNQn65iNi6d2LRZDSAsaYav3TAs/ANkbP0d6K6MqfqM4y8vWRVbLJ8z5wIJGqpc2AyVDd+uPRKfHxmoqpAROzDp6vjyWfLtE1L/o7KHqOfF6fIARZsHUBXmi6LNe/U/1Zg80ivskrlc4SGGiv6SunqslbAWa0sAHLECkA==,iv:TYcPSUFsGTdH53wru2Kep0o9MhUOvv8flrOciArDdu0=,tag:+OdiAEh7/whFEEQ0W0uAbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-03T16:53:00Z"
    mac: ENC[AES256_GCM,data:Miff8B5VXJ1e1I/QZitw06MIKmlydZyrBK4ctj7N3KfYxHU1AMgL47LKq2fA8OKHziOMd8WsqSrmLYyCe3muOLB+aHdjgUpkf0QfEAcsgykLUdfsGJywMmxqmGwPu7zSDiDU2+IpR6/DCPltRkTPa4SBoM/UEpuaVz82n1nQIGY=,iv:3j3fnUnF8L3UHRe+zd4vkB4bLPd31iGGGm22C3uA7b0=,tag:ZPtXnIBVB8ZjjoxBPoYo3A==,type:str]
    pgp:
        - created_at: "2021-07-03T16:53:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/twvmtTWS63AQ/+NKxZ70Iitey00xWxPP8XscEQN4k2hBHH27tw61mKMQRh
            4xY6y4K1kAFrXjks3rz5QHBVX2fKZyjU7jd+OA1l+qrqhlIcE6HgQU5h22UAPc4j
            nGjomPFN02d4glGDQCMcjLoHGG5qDlLJ3SbGVH15E1UsSVrl6Av0mbWrCm7RaZdv
            GWXe0iJK8beUXLqCNVaR/pxFKbaW10ODaRM9IY7h0txIP0kcQfpfLs47p8+soiW2
            9S1Gxxt0mdSg1MfkABikuXXoUApBcZgDfaNzZvW3FwW9GRjzg2I0EZR+xWpQ8jNy
            B8DtGskRUI6lFtP3obeYz3wZ0WghobfpaoXIEvhfwJPMDls9kkoXgyoIySh7VVAy
            vQNsePXTZHzYBGwEQ5Ta7lh8Q+N1+hjZnROKELXc/pYGJB7Baro1WJxF1M0DxxCk
            IMg6kggbb9n9QRsGpA8atqfxvPHtpU25qfQMxnQnZBaEAj2GVJo53LJchYEA68c4
            o4/1rIhvgkE5dGBDmHw71t/1FsZqYhdXfrXDwoB/nKD1mjKGz3PzZi+NTiYmTTIX
            CliThf77fPC7qhnV+8gExidHlOcRdl8k3KHsHU4wkG0/HVuaqtn5/f4m1W4KPRVO
            gjss1PtFaxuEOTMX3M70KySSAab1K1kFujA4hdhdIzvVomWglzRLGtEt/J5yoFfS
            XAHxZ6QHD5Mrpo2fkywSevhv9YKTA/iB45DQOsmwUaRFV7W5BXvJgxajeYD7Ge3l
            q53e5pZniH0uN/LsNQWe0RfnFVhb9mc89wQCTdCUy/KcD3UjMFz5GcOatKhg
            =gpRI
            -----END PGP MESSAGE-----
          fp: F218E6030557131BFE2B62AF9EB6C6C54B075E78
        - created_at: "2021-07-03T16:53:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA64B9baa/LIjAQ//Rq1j2SvftDcMORKheB/+NJJ+On43mvciCpysCK7iCUFO
            bAu0LriTTW0fnaVXovc5Nwupk7qXq+PhEoRFi4fJbkbD9rAQKxaei6wFo0gLlxhK
            HfmKRjXCCHkJCoJa6moVkrtvv11JB+53TbpPZNC9whnt0m/3Ucy1DVWgNw4M75hH
            4Gfb7yFccqVFY8pEc2ZXMRbSwDzbWlBG8E2CXJD+7mM+IruDQzMdXlnb38OrSj8H
            Ji3DGhh0Wz5s80efGOqObf+9Ixc3j0IoTC0gLITrRNzretl6ilvaEb+6oFZWwZja
            auDsCETPWZFLNFnOjXS76qpgQCqvOcF3WnvDfSkv2Z8LjZqucS6RH+lMenIJCi8T
            pLtWa3YmJzohhdQVfVxPyXARzBfHjoYNuDHuC8r53f/BRyEzM+cN4gxcVUzI3L+n
            b+d0yZGPxlR+IgsqiUgaS8txKT/RQfeZI2Ec7D13lG9P/RfS1XlPuAdeIQPi0ZFh
            F/yJfPRndaekB65thujCiPwtJ2xfYNWcRThr7DoeNYTK3jR7V3RRouMzbTYLaM7T
            4hj5SCmLd7udYkx1hIzGjP/1albU46zoUfPJSeTv3XjucoeX6/EvSLjFNa3EXLFP
            9wjQ4nwSDxrtkYdDsyXJ2FZdCfdyq/MhZc3F8zOT4dFjE36r9G1skR2U3X+m77/S
            XAE4nVIcQYb6ld8I0xYYMYulyxdJKEl9qAXaptPKxl26zTx/seppHtc8EEqyZuNY
            u9khdMIJ4GCab8/2cFDDkrpfyss8mxgPWF8or3ssLr3Pgw0ytfWaV/9swBVi
            =Wzk0
            -----END PGP MESSAGE-----
          fp: EE1FCDA1BD7E34481E71FCBFC72AB78A7F05099D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
