name: Create values diff on updated Helm Releases

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
    - main
    paths:
    - "cluster/**.yaml"

env:
  conf_live_branch: main

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-20.04
    outputs:
      yaml_files: "${{ steps.filter.outputs.yaml_files }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: json
        filters: |
          yaml:
            - added|modified: "**/*helm-release.yaml"

  helm:
    name: Template HelmReleases
    runs-on: ubuntu-20.04
    if: ${{ needs.changes.outputs.yaml_files != '[]' }}
    needs: changes
    strategy:
      matrix:
        file: ${{ fromJson(needs.changes.outputs.yaml_files ) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout live branch
      uses: actions/checkout@v3
      with:
        ref: ${{ env.conf_live_branch }}
        path: live
    - name: Setup Kubernetes Tools
      uses: yokawasa/action-setup-kube-tools@v0.8.0
      with:
        setup-tools: |
          helmv3
          yq
    - name: Create diff
      id: diff
      run: |
        hr_chart=$(yq e .spec.chart.spec.chart ${{ matrix.file }})
        hr_chart_source=$(yq e .spec.chart.spec.sourceRef.name ${{ matrix.file }})
        for file in $(find cluster/base/flux-system/charts/helm -name '*-charts.yaml'); do
            if [[ $(yq e .metadata.name ${file}) != ${hr_chart_source} ]]; then continue; fi
            hr_url=$(yq e .spec.url ${file}); break;
        done
        hr_live_version=$(yq e .spec.chart.spec.version live/${{ matrix.file }})
        hr_pr_version=$(yq e .spec.chart.spec.version ${{ matrix.file }})

        helm repo add pr "$hr_url"
        resources_live=$(helm show values pr/"$hr_chart" --version "$hr_live_version" || true)
        echo "$resources_live"
        echo "#####################################################"
        resources_pr=$(helm show values pr/"$hr_chart" --version "$hr_pr_version" || true)
        echo "$resources_pr"
        echo "#####################################################"
        diff=$((diff -u <(echo "$resources_live") <(echo "$resources_pr") || true) | tail +3)
        echo "$diff"
        message="Path: \`${{ matrix.file }}\`"
        if [ "$hr_live_version" != "$hr_pr_version" ]; then
            message="$message"$'\n'"Version: \`$hr_live_version\` -> \`$hr_pr_version\`"
        fi
        message="$message"$'\n'$'\n'
        if [ -z "$diff" ]; then
            message="$message"'```'$'\n'"No changes in detected in resources"$'\n''```'
        else
            message="$message"'```diff'$'\n'"$diff"$'\n''```'
        fi
        echo "::set-output name=message::$(echo "$message" | jq --raw-input --slurp)"

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ matrix.file }}

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: "${{ fromJSON(steps.diff.outputs.message) }}"
        edit-mode: replace
